const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const $=(s,p=document)=>p.querySelector(s);

function route(name,authMode){
  $$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));
  $$('.preview-nav [data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===name));
  if(name==='auth'&&authMode) setAuth(authMode);
  if(!location.hash.startsWith(`#${name}`)) history.pushState(null,'',`#${name}`);
  scrollTo({top:0,behavior:'instant'});
}
function setAuth(mode){
  $$('[data-auth-tab]').forEach(b=>{const active=b.dataset.authTab===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});
  $$('[data-auth-panel]').forEach(p=>p.hidden=p.dataset.authPanel!==mode);
  $('.reset').hidden=true;
}
$$('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();route(el.dataset.route,el.dataset.auth)}));
$$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>setAuth(b.dataset.authTab)));

$$('.chart nav button,.outcomes nav button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
$$('.role-select button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));

const stepCopy={
  brief:['STEP 01 / CAMPAIGN BRIEF','Start with the outcome<br>you need to create.','Define campaign goals, qualified events, dates, creator criteria, and deliverables before invitations go out.'],
  invite:['STEP 02 / CREATOR INVITES','Bring the right creators<br>into one workspace.','Invite creators, share the brief, confirm participation, and keep every campaign conversation connected.'],
  track:['STEP 03 / ACTIVITY TRACKING','Capture the work<br>as it happens.','Collect deliverables and first-party links while keeping submitted evidence distinct from verified platform events.'],
  prove:['STEP 04 / OUTCOME REPORT','Connect every result<br>to its source.','See the creator, activity, tracking event, conversion, and qualified outcome in one auditable evidence trail.']
};
$$('[data-step]').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=stepCopy[b.dataset.step],box=$('.step-preview>div');box.querySelector('span').textContent=c[0];box.querySelector('h3').innerHTML=c[1];box.querySelector('p').textContent=c[2]}));

$$('[data-password]').forEach(b=>b.addEventListener('click',()=>{const input=b.parentElement.querySelector('input'),show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Hide':'Show';b.setAttribute('aria-pressed',String(show))}));
$('[data-login]')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,email=form.email,password=form.password;form.querySelectorAll('label').forEach(l=>l.classList.remove('invalid'));$('.auth-error').hidden=true;if(!email.value.includes('@'))email.closest('label').classList.add('invalid');if(!password.value)password.closest('label').classList.add('invalid');if(!email.value.includes('@')||!password.value)return;const button=form.querySelector('.auth-submit');button.disabled=true;button.querySelector('.loader').classList.add('show');button.querySelector('span').textContent='Logging in';setTimeout(()=>{button.disabled=false;button.querySelector('.loader').classList.remove('show');button.querySelector('span').textContent='Log in';email.value==='demo@linkary.xyz'?route('dashboard'):$('.auth-error').hidden=false},700)});
$('[data-reset]')?.addEventListener('click',()=>{$$('[data-auth-panel]').forEach(p=>p.hidden=true);$('.reset').hidden=false});
$('[data-reset-back]')?.addEventListener('click',()=>setAuth('login'));

$('[data-notify]')?.addEventListener('click',e=>{const panel=$('.notify-panel'),open=panel.hidden;panel.hidden=!open;e.currentTarget.setAttribute('aria-expanded',String(open))});
$('[data-close-notify]')?.addEventListener('click',()=>$('.notify-panel').hidden=true);
$('[data-modal]')?.addEventListener('click',()=>{$('.backdrop').hidden=false;$('.modal input')?.focus()});
$$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>$('.backdrop').hidden=true));
$('[data-create]')?.addEventListener('click',()=>{$('.backdrop').hidden=true;const t=$('.toast');t.hidden=false;setTimeout(()=>t.hidden=true,3500)});
$('.toast button')?.addEventListener('click',()=>$('.toast').hidden=true);
$('.menu')?.addEventListener('click',()=>$('.dashboard-page').classList.toggle('sidebar-open'));
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(!$('.backdrop').hidden)$('.backdrop').hidden=true;if(!$('.notify-panel').hidden)$('.notify-panel').hidden=true;$('.dashboard-page').classList.remove('sidebar-open')});

$$('details').forEach(d=>d.addEventListener('toggle',()=>{const i=d.querySelector('summary i');if(i)i.textContent=d.open?'−':'+'}));
const initial=location.hash.slice(1);const initialTop=initial.split('/')[0];if(['home','auth','dashboard','library'].includes(initialTop))route(initialTop);else route('home');

/* Working dashboard navigation and demo views */
const dashboardMain=$('.dash-main');
const overviewMarkup=dashboardMain?.innerHTML||'';
const appViews={
  campaigns:()=>`<div class="subview-head"><div><span>CAMPAIGN OPERATIONS</span><h1 tabindex="-1">Campaigns</h1><p>Plan, launch, and monitor creator campaigns from one workspace.</p></div><button class="btn brand" data-modal>Create campaign ＋</button></div><div class="sub-metrics"><article><small>LIVE</small><b>8</b><span>3 ending this month</span></article><article><small>DRAFTS</small><b>4</b><span>2 ready to launch</span></article><article><small>NEEDS REVIEW</small><b>3</b><span>6 deliverables waiting</span></article><article><small>30D OUTCOMES</small><b>1,284</b><span class="good">↗ 8.2%</span></article></div><section class="sub-card"><div class="sub-toolbar"><div class="search-field">⌕ <input placeholder="Search campaigns"></div><div><button class="filter-chip active">All 15</button><button class="filter-chip">Live 8</button><button class="filter-chip">Draft 4</button><button class="filter-chip">Review 3</button></div></div><div class="campaign-grid"><article><header><i class="thumb orange">SL</i><span class="status live">Live</span></header><h3>Summer launch</h3><p>Community growth · 12 creators</p><div class="campaign-stat"><span><small>Qualified joins</small><b>1,284</b></span><span><small>Progress</small><b>68%</b></span></div><i class="progress"><b style="width:68%"></b></i><footer><small>Ends Sep 12</small><button data-demo-toast="Opening campaign workspace">Open →</button></footer></article><article><header><i class="thumb purple">CR</i><span class="status review">Needs review</span></header><h3>Creator refresh</h3><p>Profile claims · 6 creators</p><div class="campaign-stat"><span><small>Profile claims</small><b>482</b></span><span><small>Progress</small><b>43%</b></span></div><i class="progress"><b style="width:43%"></b></i><footer><small>Ends Sep 20</small><button data-app-view="activities">Review →</button></footer></article><article><header><i class="thumb green">TG</i><span class="status scheduled">Scheduled</span></header><h3>Telegram growth</h3><p>Community joins · 2 creators</p><div class="campaign-stat"><span><small>Starts in</small><b>8 days</b></span><span><small>Setup</small><b>18%</b></span></div><i class="progress"><b style="width:18%"></b></i><footer><small>Starts Sep 08</small><button data-demo-toast="Campaign setup opened">Continue →</button></footer></article></div></section>`,
  creators:()=>`<div class="subview-head"><div><span>CREATOR NETWORK</span><h1 tabindex="-1">Creators</h1><p>Discover creators with campaign evidence, reliability, and verified outcomes.</p></div><button class="btn brand" data-demo-toast="Invite flow opened">Invite creator ＋</button></div><section class="sub-card"><div class="sub-toolbar"><div class="search-field">⌕ <input placeholder="Search name, handle, or niche"></div><div><button class="filter-chip active">Recommended</button><button class="filter-chip">Shortlisted 12</button><button class="filter-chip">Past collaborators</button></div></div><div class="creator-cards"><article><div><i class="avatar orange profile-avatar">AK</i><span class="status complete">✓ Verified</span></div><h3>Alex Kim <small>@alexk</small></h3><p>Social video · Product launches</p><dl><div><dt>Campaigns</dt><dd>24</dd></div><div><dt>Delivery</dt><dd>96%</dd></div><div><dt>Avg result</dt><dd>4.8×</dd></div></dl><footer><button class="btn outline small" data-demo-toast="Alex added to shortlist">＋ Shortlist</button><button class="btn brand small" data-demo-toast="Creator profile opened">View profile</button></footer></article><article><div><i class="avatar green profile-avatar">MN</i><span class="status complete">✓ Verified</span></div><h3>Mila North <small>@milanorth</small></h3><p>Community · Educational content</p><dl><div><dt>Campaigns</dt><dd>18</dd></div><div><dt>Delivery</dt><dd>100%</dd></div><div><dt>Avg result</dt><dd>4.2×</dd></div></dl><footer><button class="btn outline small" data-demo-toast="Mila added to shortlist">＋ Shortlist</button><button class="btn brand small" data-demo-toast="Creator profile opened">View profile</button></footer></article><article class="creator-unavailable"><div><i class="avatar dark profile-avatar">JS</i><span class="status review">Partial data</span></div><h3>Jo Social <small>@jo.social</small></h3><p>Lifestyle · Short-form video</p><dl><div><dt>Campaigns</dt><dd>9</dd></div><div><dt>Delivery</dt><dd>92%</dd></div><div><dt>Avg result</dt><dd>—</dd></div></dl><small class="data-note">Instagram connection needs reauthorization.</small><footer><button class="btn outline small" data-demo-toast="Reauthorization requested">Request reauth</button></footer></article></div></section>`,
  activities:()=>`<div class="subview-head"><div><span>DELIVERABLE OPERATIONS</span><h1 tabindex="-1">Activities</h1><p>Review creator work and keep every approval attached to the campaign record.</p></div><button class="btn brand" data-demo-toast="Activity request opened">Request activity ＋</button></div><div class="kanban"><section><header><b>Requested</b><span>4</span></header><article><small>SUMMER LAUNCH</small><h3>Launch carousel</h3><p>@alexk · 8 slides</p><footer><span>Due tomorrow</span><i class="avatar orange">AK</i></footer></article><article><small>CREATOR REFRESH</small><h3>Profile walkthrough</h3><p>@milanorth · Short video</p><footer><span>Due Sep 04</span><i class="avatar green">MN</i></footer></article></section><section><header><b>In review</b><span class="orange-count">3</span></header><article class="selected-card"><small>SUMMER LAUNCH</small><h3>Product walkthrough</h3><p>@jo.social · 0:42</p><div class="media-preview">▶<span>00:42</span></div><footer><button data-demo-toast="Revision requested">Request revision</button><button class="approve" data-demo-toast="Deliverable approved">Approve</button></footer></article></section><section><header><b>Approved</b><span>17</span></header><article><small>SUMMER LAUNCH</small><h3>Launch explainer</h3><p>@milanorth · Reel</p><footer><span class="status complete">✓ Approved</span><i class="avatar green">MN</i></footer></article><article><small>CREATOR REFRESH</small><h3>Profile carousel</h3><p>@alexk · 6 slides</p><footer><span class="status complete">✓ Approved</span><i class="avatar orange">AK</i></footer></article></section></div>`,
  'tracking-links':()=>`<div class="subview-head"><div><span>FIRST-PARTY ATTRIBUTION</span><h1 tabindex="-1">Tracking links</h1><p>Create Linkary-owned links and connect creator activity to downstream outcomes.</p></div><button class="btn brand" data-demo-toast="New tracking-link form opened">Create link ＋</button></div><div class="sub-metrics"><article><small>ACTIVE LINKS</small><b>42</b><span>Across 8 campaigns</span></article><article><small>30D CLICKS</small><b>24,842</b><span class="good">↗ 21.6%</span></article><article><small>CONVERSIONS</small><b>4,892</b><span class="good">↗ 14.8%</span></article><article><small>CONVERSION RATE</small><b>19.7%</b><span>Qualified: 5.2%</span></article></div><section class="sub-card"><div class="sub-toolbar"><div class="search-field">⌕ <input placeholder="Search links or destination"></div><button class="filter-chip">≡ Filters</button></div><div class="link-table"><header><span>Link</span><span>Creator / campaign</span><span>Clicks</span><span>Conversions</span><span>Status</span><span></span></header><article><b>l.linkary.xyz/summer-ak<small>linkary.xyz/join</small></b><span>@alexk · Summer launch</span><strong>8,482</strong><strong>1,284</strong><i class="status live">Active</i><button data-demo-toast="Link copied to clipboard">Copy</button></article><article><b>l.linkary.xyz/launch-mn<small>app.linkary.xyz/register</small></b><span>@milanorth · Summer launch</span><strong>6,120</strong><strong>982</strong><i class="status live">Active</i><button data-demo-toast="Link copied to clipboard">Copy</button></article><article class="muted-row"><b>l.linkary.xyz/old-js<small>Destination unavailable</small></b><span>@jo.social · Archive</span><strong>—</strong><strong>—</strong><i class="status review">Paused</i><button data-demo-toast="Edit link opened">Fix</button></article></div></section>`,
  analytics:()=>`<div class="subview-head"><div><span>CAMPAIGN INTELLIGENCE</span><h1 tabindex="-1">Analytics</h1><p>Compare creator activity with attributed and qualified outcomes.</p></div><div><button class="btn outline" data-demo-toast="Report export prepared">Export report</button> <button class="btn brand" data-demo-toast="Share link copied">Share ↗</button></div></div><div class="analytics-layout"><section class="sub-card analytics-main"><header><span><small>ATTRIBUTED OUTCOMES · 30D</small><b>Performance by source</b></span><div><button class="filter-chip active">Conversions</button><button class="filter-chip">Qualified</button></div></header><div class="analytics-number"><b>4,892</b><span>↗ 14.8%</span><small>Updated 2 minutes ago · First-party events</small></div><div class="analytics-bars"><i style="height:35%"></i><i style="height:42%"></i><i style="height:40%"></i><i style="height:55%"></i><i style="height:68%"></i><i style="height:63%"></i><i style="height:78%"></i><i style="height:72%"></i><i style="height:91%"></i><i style="height:86%"></i><i style="height:100%"></i></div><footer><span>Aug 02</span><span>Aug 09</span><span>Aug 16</span><span>Aug 23</span><span>Aug 31</span></footer></section><section class="sub-card source-panel"><header><small>TOP SOURCES</small><b>Share of conversions</b></header><ol><li><i class="avatar orange">AK</i><b>@alexk<small>Summer launch</small></b><span>38%</span></li><li><i class="avatar green">MN</i><b>@milanorth<small>Summer launch</small></b><span>27%</span></li><li><i class="avatar purple">JS</i><b>@jo.social<small>Creator refresh</small></b><span>18%</span></li><li><i class="avatar dark">＋</i><b>Other sources<small>18 links</small></b><span>17%</span></li></ol><div class="quality-note"><i>i</i><p><b>Attribution quality: healthy</b><span>93% of conversions have a complete first-party source path.</span></p></div></section></div>`,
  profiles:()=>`<div class="subview-head"><div><span>PUBLIC IDENTITIES</span><h1 tabindex="-1">Profiles</h1><p>Manage the public creator and project profiles connected to your account.</p></div><button class="btn brand" data-demo-toast="Profile creation opened">Create profile ＋</button></div><section class="sub-card"><div class="profile-list"><article><div class="public-cover orange-cover"></div><div class="public-profile-body"><i class="avatar orange profile-avatar">LM</i><span class="status live">Published</span><h3>Linkary Marketing</h3><p>linkary.xyz/linkary · Project profile</p><dl><span><dt>Views · 30D</dt><dd>8,420</dd></span><span><dt>Campaigns</dt><dd>8</dd></span><span><dt>Team</dt><dd>4</dd></span></dl><footer><button class="btn outline small" data-demo-toast="Public profile opened">View public</button><button class="btn brand small" data-demo-toast="Profile editor opened">Edit profile</button></footer></div></article><article><div class="public-cover dark-cover"></div><div class="public-profile-body"><i class="avatar dark profile-avatar">MM</i><span class="status review">Draft</span><h3>Muaz M.</h3><p>Username not claimed · Creator profile</p><div class="empty-inline"><b>Finish your creator profile</b><span>Claim a username and prove ownership of your X account.</span></div><footer><button class="btn brand small" data-demo-toast="Profile setup opened">Continue setup</button></footer></div></article></div></section>`,
  integrations:()=>`<div class="subview-head"><div><span>CONNECTED DATA</span><h1 tabindex="-1">Integrations</h1><p>Manage social, community, identity, and reporting connections.</p></div></div><div class="integration-grid"><article><header><i>𝕏</i><span class="status live">Connected</span></header><h3>X</h3><p>Identity verification and submitted campaign evidence.</p><small>Connected as @linkary · Synced 4m ago</small><button data-demo-toast="X connection settings opened">Manage</button></article><article><header><i>◎</i><span class="status review">Expires soon</span></header><h3>Instagram</h3><p>Authorized profile, content, and engagement metrics.</p><small>Authorization expires in 3 days</small><button class="warning-button" data-demo-toast="Instagram reauthorization opened">Reconnect</button></article><article><header><i>▶</i><span class="status live">Connected</span></header><h3>YouTube</h3><p>Official video statistics and campaign content.</p><small>2 channels · Synced 18m ago</small><button data-demo-toast="YouTube settings opened">Manage</button></article><article><header><i>✈</i><span class="status live">Connected</span></header><h3>Telegram</h3><p>Campaign invite links and member join/leave events.</p><small>3 communities · Live webhook</small><button data-demo-toast="Telegram settings opened">Manage</button></article><article><header><i>◫</i><span class="status scheduled">Available</span></header><h3>Resend</h3><p>Business invitations and lifecycle notifications.</p><small>Not configured</small><button data-demo-toast="Resend setup opened">Connect</button></article><article class="integration-unavailable"><header><i>◌</i><span class="status">Unavailable</span></header><h3>Meta public fallback</h3><p>Public fallback is not enabled for this workspace.</p><small>No data is being simulated.</small><button disabled>Unavailable</button></article></div>`,
  settings:()=>`<div class="subview-head"><div><span>WORKSPACE CONFIGURATION</span><h1 tabindex="-1">Settings</h1><p>Manage workspace identity, members, notifications, billing, and data policy.</p></div><button class="btn brand" data-demo-toast="Settings saved">Save changes</button></div><div class="settings-layout"><nav><button class="active">General</button><button>Members</button><button>Notifications</button><button>Billing account</button><button>Privacy & data</button><button>Audit log</button></nav><section class="sub-card settings-form"><header><h2>Workspace details</h2><p>Information used throughout the authenticated application.</p></header><label>Workspace name<input value="Linkary Marketing"></label><label>Workspace URL<div><span>app.linkary.xyz/</span><input value="linkary-marketing"></div></label><label>Default reporting timezone<select><option>Europe/Berlin (UTC+02:00)</option></select></label><label>Campaign data retention<select><option>Keep according to plan limits</option></select><small>Privacy and compliance deletion requests override this setting.</small></label><div class="settings-toggle"><span><b>Weekly performance digest</b><small>Email workspace owners every Monday.</small></span><button role="switch" aria-checked="true"><i></i></button></div><aside><b>Organization deletion</b><p>Normal users can archive, restore, or transfer ownership. Permanent deletion is restricted to Superadmin/compliance workflows.</p><button class="btn outline small" data-demo-toast="Archive workflow opened">Archive workspace</button></aside></section></div>`
};
const appNames={overview:'Overview',campaigns:'Campaigns',creators:'Creators',activities:'Activities','tracking-links':'Tracking links',analytics:'Analytics',profiles:'Profiles',integrations:'Integrations',settings:'Settings'};
$$('.sidebar nav button').forEach(b=>{const label=b.querySelector('span')?.textContent.trim();const key=Object.keys(appNames).find(k=>appNames[k]===label);if(key)b.dataset.appView=key});
function wireSubview(){
  $$('[data-app-view]',dashboardMain).forEach(b=>b.addEventListener('click',()=>showAppView(b.dataset.appView,true)));
  $$('[data-demo-toast]',dashboardMain).forEach(b=>b.addEventListener('click',()=>showDemoToast(b.dataset.demoToast)));
  $('[data-modal]',dashboardMain)?.addEventListener('click',()=>{$('.backdrop').hidden=false;$('.modal input')?.focus()});
  $$('.filter-chip',dashboardMain).forEach(b=>b.addEventListener('click',()=>{const group=b.parentElement;group.querySelectorAll('.filter-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
}
function showDemoToast(message){const t=$('.toast');t.querySelector('b').childNodes[0].textContent=message;t.hidden=false;setTimeout(()=>t.hidden=true,2600)}
function showAppView(view='overview',writeHash=false){
  if(!dashboardMain)return;
  dashboardMain.innerHTML=view==='overview'?overviewMarkup:(appViews[view]?.()||overviewMarkup);
  $$('.sidebar nav button').forEach(b=>{const on=b.dataset.appView===view;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});
  $('.topbar p b').textContent=appNames[view]||'Overview';
  $('.dashboard-page').classList.remove('sidebar-open');
  if(writeHash)history.pushState(null,'',`#dashboard/${view}`);
  wireSubview();
  dashboardMain.querySelector('h1')?.focus({preventScroll:true});
}
$$('.sidebar nav button[data-app-view]').forEach(b=>b.addEventListener('click',()=>showAppView(b.dataset.appView,true)));
document.addEventListener('click',e=>{const b=e.target.closest('[data-demo-toast]');if(b&&!dashboardMain.contains(b))showDemoToast(b.dataset.demoToast)});
window.addEventListener('hashchange',()=>{const [top,sub]=location.hash.slice(1).split('/');if(top==='dashboard'){route('dashboard');showAppView(sub||'overview',false)}});
const dashboardHash=location.hash.slice(1).split('/');if(dashboardHash[0]==='dashboard')showAppView(dashboardHash[1]||'overview',false);
$$('.preview-nav [data-route="dashboard"]').forEach(b=>b.addEventListener('click',()=>showAppView('overview',true)));
