import type { Env } from '../env';
import { requireDb } from '../env';
import { Db } from '../db/client';
import { ensureAttributionSchema } from '../db/attributionSchema';
import { HttpError, json, readJson } from '../http';
import { requireAuth, verifyCsrf } from '../auth/session';
import { requireOperationalProjectAccess } from './organizations';

const id = () => `act_${crypto.randomUUID().replace(/-/g, '')}`;
const now = () => new Date().toISOString();
async function authorize(db: Db, userId: string, campaignId: string, write = false) { await ensureAttributionSchema(db); const campaign = await db.first<{ organization_id: string }>('SELECT organization_id FROM campaigns WHERE id = ?', [campaignId]); if (!campaign) throw new HttpError(404, 'Campaign not found', 'campaign_not_found'); await requireOperationalProjectAccess(db, userId, campaign.organization_id, write); return campaign; }
export async function listActivities(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); const campaignId = new URL(request.url).searchParams.get('campaignId'); if (!campaignId) throw new HttpError(400, 'campaignId is required', 'campaign_required'); const db = new Db(requireDb(env)); await authorize(db, auth.user.id, campaignId); return json({ activities: await db.all('SELECT id, title, activity_type, destination_url, planned_cost_usd, status, created_at FROM campaign_activities WHERE campaign_id = ? ORDER BY created_at DESC', [campaignId]) }); }
export async function createActivity(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const body = await readJson<{ campaignId?: string; title?: string; activityType?: string; destinationUrl?: string; plannedCostUsd?: number }>(request); if (!body.campaignId || !body.title?.trim()) throw new HttpError(400, 'Campaign and activity title are required', 'invalid_activity'); const allowed = new Set(['creator_content', 'community_placement', 'website', 'video', 'other']); if (!body.activityType || !allowed.has(body.activityType)) throw new HttpError(400, 'Invalid activity type', 'invalid_activity_type'); let destination: string | null = null; if (body.destinationUrl) { try { const url = new URL(body.destinationUrl); if (!['https:', 'http:'].includes(url.protocol)) throw new Error(); destination = url.toString(); } catch { throw new HttpError(400, 'Invalid destination URL', 'invalid_url'); } } const db = new Db(requireDb(env)); await authorize(db, auth.user.id, body.campaignId, true); const activityId = id(); const timestamp = now(); await db.run('INSERT INTO campaign_activities (id, campaign_id, title, activity_type, destination_url, planned_cost_usd, status, created_by_user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, \'planned\', ?, ?, ?)', [activityId, body.campaignId, body.title.trim().slice(0, 140), body.activityType, destination, typeof body.plannedCostUsd === 'number' ? body.plannedCostUsd : null, auth.user.id, timestamp, timestamp]); return json({ id: activityId }, { status: 201 }); }
