import type { Env } from '../env';
import { requireDb } from '../env';
import { Db } from '../db/client';
import { HttpError, json, readJson } from '../http';
import { requireAuth, verifyCsrf } from '../auth/session';
import { organizationMembership, requireOperationalProjectAccess } from './organizations';
const id = () => `cev_${crypto.randomUUID().replace(/-/g, '')}`; const now = () => new Date().toISOString();
export async function createConversion(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const body = await readJson<{ trackedLinkId?: string; eventKey?: string; eventType?: string; valueUsd?: number; occurredAt?: string }>(request); if (!body.trackedLinkId || !body.eventKey?.trim() || !body.eventType?.trim()) throw new HttpError(400, 'Tracking link, external outcome ID, and outcome type are required', 'invalid_conversion'); const db = new Db(requireDb(env)); const link = await db.first<{ organization_id: string; campaign_id: string | null; activity_id: string | null }>('SELECT organization_id, campaign_id, activity_id FROM tracked_links WHERE id = ?', [body.trackedLinkId]); if (!link) throw new HttpError(404, 'Tracking link not found', 'tracking_not_found'); await requireOperationalProjectAccess(db, auth.user.id, link.organization_id, true); const eventKey = body.eventKey.trim().slice(0, 180); const existing = await db.first<{ id: string }>('SELECT id FROM conversion_events WHERE organization_id = ? AND external_event_key = ?', [link.organization_id, eventKey]); if (existing) return json({ ok: true, id: existing.id, duplicate: true }); const conversionId = id(); await db.run('INSERT INTO conversion_events (id, organization_id, campaign_id, activity_id, tracked_link_id, external_event_key, event_type, value_usd, source, attribution_confidence, occurred_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, \'manual\', \'manual\', ?, ?)', [conversionId, link.organization_id, link.campaign_id, link.activity_id, body.trackedLinkId, eventKey, body.eventType.trim().slice(0, 80), typeof body.valueUsd === 'number' ? body.valueUsd : null, body.occurredAt || now(), now()]); return json({ ok: true, id: conversionId, duplicate: false }, { status: 201 }); }
export async function campaignOutcomeSummary(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); const campaignId = new URL(request.url).searchParams.get('campaignId'); if (!campaignId) throw new HttpError(400, 'campaignId is required', 'campaign_required'); const db = new Db(requireDb(env)); const campaign = await db.first<{ organization_id: string }>('SELECT organization_id FROM campaigns WHERE id = ?', [campaignId]); if (!campaign || !(await organizationMembership(db, auth.user.id, campaign.organization_id))) throw new HttpError(403, 'Campaign access denied', 'forbidden'); const summary = await db.first<{ conversions: number; value_usd: number; tracked_clicks: number }>('SELECT (SELECT COUNT(*) FROM conversion_events WHERE campaign_id = ?) AS conversions, COALESCE((SELECT SUM(value_usd) FROM conversion_events WHERE campaign_id = ?), 0) AS value_usd, COALESCE((SELECT COUNT(*) FROM tracked_link_clicks c JOIN tracked_links t ON t.id = c.tracked_link_id WHERE t.campaign_id = ?), 0) AS tracked_clicks', [campaignId, campaignId, campaignId]); return json({ summary }); }
