import type { Env } from '../env';
import { requireDb } from '../env';
import { Db } from '../db/client';
import { HttpError, json, readJson } from '../http';
import { requireAuth, verifyCsrf } from '../auth/session';
import { organizationMembership, requireOperationalProjectAccess } from './organizations';
const id = (prefix: string) => `${prefix}_${crypto.randomUUID().replace(/-/g, '')}`; const now = () => new Date().toISOString();
export async function listNetworkEntities(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); const organizationId = new URL(request.url).searchParams.get('organizationId'); if (!organizationId) throw new HttpError(400, 'organizationId is required', 'organization_required'); const db = new Db(requireDb(env)); if (!(await organizationMembership(db, auth.user.id, organizationId))) throw new HttpError(403, 'Network access denied', 'forbidden'); return json({ entities: await db.all(`SELECT id, entity_type, display_name, primary_handle, primary_url, verification_status, notes, created_at FROM project_network_entities WHERE organization_id = ? ORDER BY created_at DESC`, [organizationId]) }); }
export async function createNetworkEntity(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const body = await readJson<{ organizationId?: string; entityType?: 'creator' | 'community'; displayName?: string; handle?: string; url?: string; notes?: string }>(request); if (!body.organizationId || !['creator', 'community'].includes(body.entityType || '') || !body.displayName?.trim()) throw new HttpError(400, 'Project, type, and name are required', 'invalid_network_entity'); let url: string | null = null; if (body.url) { try { const parsed = new URL(body.url); if (!['https:', 'http:'].includes(parsed.protocol)) throw new Error(); url = parsed.toString(); } catch { throw new HttpError(400, 'Invalid profile URL', 'invalid_url'); } } const db = new Db(requireDb(env)); await requireOperationalProjectAccess(db, auth.user.id, body.organizationId, true); const timestamp = now(); const entityId = id('net'); await db.run(`INSERT INTO project_network_entities (id, organization_id, entity_type, display_name, primary_handle, primary_url, verification_status, notes, created_by_user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'unverified', ?, ?, ?, ?)`, [entityId, body.organizationId, body.entityType, body.displayName.trim().slice(0, 120), body.handle?.trim().replace(/^@/, '').slice(0, 80) || null, url, body.notes?.trim().slice(0, 500) || '', auth.user.id, timestamp, timestamp]); return json({ id: entityId }, { status: 201 }); }
export async function assignNetworkEntity(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const body = await readJson<{ activityId?: string; entityId?: string; role?: string }>(request); if (!body.activityId || !body.entityId) throw new HttpError(400, 'Activity and network entity are required', 'invalid_assignment'); const db = new Db(requireDb(env)); const activity = await db.first<{ organization_id: string }>(`SELECT c.organization_id FROM campaign_activities a JOIN campaigns c ON c.id = a.campaign_id WHERE a.id = ?`, [body.activityId]); const entity = activity && await db.first<{ id: string }>(`SELECT id FROM project_network_entities WHERE id = ? AND organization_id = ?`, [body.entityId, activity.organization_id]); if (!activity || !entity) throw new HttpError(404, 'Activity or Project network entity not found', 'assignment_not_found'); await requireOperationalProjectAccess(db, auth.user.id, activity.organization_id, true); await db.run(`INSERT INTO campaign_activity_participants (id, activity_id, entity_id, participation_role, created_at) VALUES (?, ?, ?, ?, ?) ON CONFLICT(activity_id, entity_id) DO UPDATE SET participation_role = excluded.participation_role`, [id('cap'), body.activityId, body.entityId, ['creator', 'community_host', 'contributor', 'distribution_partner'].includes(body.role || '') ? body.role : 'contributor', now()]); return json({ ok: true }); }
