import type { Env } from '../env';
import { requireDb } from '../env';
import { Db } from '../db/client';
import { json } from '../http';
import { requireAuth, verifyCsrf } from '../auth/session';
export type NotificationInput = { userId: string; type: string; title: string; body: string; href?: string | null; entityType?: string | null; entityId?: string | null; dedupeKey?: string | null };
const id = () => `ntf_${crypto.randomUUID().replace(/-/g, '')}`;
export async function createNotification(db: Db, input: NotificationInput): Promise<void> { await db.run('INSERT OR IGNORE INTO notifications (id,user_id,type,title,body,href,entity_type,entity_id,dedupe_key,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)', [id(), input.userId, input.type.slice(0,80), input.title.slice(0,200), input.body.slice(0,1000), input.href?.slice(0,500) || null, input.entityType?.slice(0,80) || null, input.entityId?.slice(0,120) || null, input.dedupeKey?.slice(0,200) || null, new Date().toISOString()]); }
export async function listNotifications(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); const db = new Db(requireDb(env)); const notifications = await db.all('SELECT id,type,title,body,href,entity_type,entity_id,read_at,created_at FROM notifications WHERE user_id = ? ORDER BY created_at DESC LIMIT 50', [auth.user.id]); const row = await db.first<{ count: number }>('SELECT COUNT(*) AS count FROM notifications WHERE user_id = ? AND read_at IS NULL', [auth.user.id]); return json({ notifications, unreadCount: Number(row?.count || 0) }); }
export async function markNotificationRead(request: Request, env: Env, notificationId: string): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const db = new Db(requireDb(env)); await db.run('UPDATE notifications SET read_at = COALESCE(read_at, ?) WHERE id = ? AND user_id = ?', [new Date().toISOString(), notificationId, auth.user.id]); return json({ ok: true }); }
export async function markAllNotificationsRead(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const db = new Db(requireDb(env)); await db.run('UPDATE notifications SET read_at = ? WHERE user_id = ? AND read_at IS NULL', [new Date().toISOString(), auth.user.id]); return json({ ok: true }); }
