import type { Env } from '../env';
import { requireDb } from '../env';
import { Db } from '../db/client';
import type { ProfileBlockRow, ProfileRow } from '../db/models';
import { HttpError, html, json, readJson } from '../http';
import { publicProfileUrl } from '../urls';
import { requireAuth, verifyCsrf } from '../auth/session';
import { organizationMembership } from './organizations';

function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char] || char); }
function safeJson(value: string): unknown { try { return JSON.parse(value); } catch { return {}; } }

export async function getPublishedProfile(username: string, env: Env): Promise<{ profile: ProfileRow; blocks: ProfileBlockRow[] }> {
  const db = new Db(requireDb(env));
  const profile = await db.first<ProfileRow>(`SELECT * FROM profiles WHERE username = ? AND visibility = 'published' LIMIT 1`, [username.toLowerCase()]);
  if (!profile) throw new HttpError(404, 'Profile not found', 'profile_not_found');
  const blocks = await db.all<ProfileBlockRow>(`SELECT * FROM profile_blocks WHERE profile_id = ? AND enabled = 1 ORDER BY position ASC`, [profile.id]);
  return { profile, blocks };
}

export async function publicProfileJson(username: string, env: Env): Promise<Response> {
  const { profile, blocks } = await getPublishedProfile(username, env);
  return json({ profile: { id: profile.id, username: profile.username, displayName: profile.display_name, type: profile.profile_type, bio: profile.bio, avatarUrl: profile.avatar_url, verificationStatus: profile.verification_status }, blocks: blocks.map((block) => ({ id: block.id, type: block.block_type, title: block.title, url: block.url, config: safeJson(block.config_json) })) }, { headers: { 'cache-control': 'public, max-age=60, s-maxage=300' } });
}

export async function renderPublicProfile(request: Request, env: Env, username: string): Promise<Response> {
  const { profile, blocks } = await getPublishedProfile(username, env); const canonical = publicProfileUrl(request, env, profile.username); const title = profile.seo_title || `${profile.display_name} | Linkary`; const description = profile.seo_description || profile.bio || `Verified ${profile.profile_type} profile on Linkary.`;
  const blockHtml = blocks.map((block) => block.url ? `<a class="profile-link" href="${escapeHtml(block.url)}" rel="noopener noreferrer">${escapeHtml(block.title || block.url)}</a>` : '').join('\n'); const structuredData = JSON.stringify({ '@context': 'https://schema.org', '@type': profile.profile_type === 'project' ? 'Organization' : 'Person', name: profile.display_name, url: canonical, description }).replace(/</g, '\\u003c');
  return html(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><link rel="canonical" href="${escapeHtml(canonical)}"><meta property="og:type" content="profile"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${escapeHtml(canonical)}"><meta name="twitter:card" content="summary"><script type="application/ld+json">${structuredData}</script></head><body><main><article><div>Verified ${escapeHtml(profile.profile_type)}</div><h1>${escapeHtml(profile.display_name)}</h1><div>@${escapeHtml(profile.username)}</div><p>${escapeHtml(profile.bio || '')}</p><div>${blockHtml}</div></article><footer>Powered by Linkary</footer></main></body></html>`, { headers: { 'cache-control': 'public, max-age=60, s-maxage=300' } });
}

export async function renderSitemap(request: Request, env: Env): Promise<Response> { const db = new Db(requireDb(env)); const rows = await db.all<{ username: string; updated_at: string }>(`SELECT username, updated_at FROM profiles WHERE visibility = 'published' ORDER BY updated_at DESC LIMIT 50000`); const urls = rows.map((row) => `<url><loc>${escapeHtml(publicProfileUrl(request, env, row.username))}</loc><lastmod>${escapeHtml(row.updated_at.slice(0, 10))}</lastmod></url>`).join(''); return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`, { headers: { 'content-type': 'application/xml; charset=utf-8', 'cache-control': 'public, max-age=300, s-maxage=3600' } }); }

async function canEditProfile(db: Db, userId: string, profile: ProfileRow): Promise<boolean> { if (profile.profile_type === 'creator') return profile.owner_user_id === userId; if (!profile.organization_id) return false; const membership = await organizationMembership(db, userId, profile.organization_id); return Boolean(membership && ['owner', 'admin', 'marketing_manager'].includes(membership.role)); }
async function requireEditableProfile(db: Db, userId: string, profileId: string): Promise<ProfileRow> { const profile = await db.first<ProfileRow>(`SELECT * FROM profiles WHERE id = ?`, [profileId]); if (!profile) throw new HttpError(404, 'Profile not found', 'profile_not_found'); if (!(await canEditProfile(db, userId, profile))) throw new HttpError(403, 'Profile edit access denied', 'forbidden'); return profile; }
function cleanText(value: unknown, max: number): string | null { if (value === undefined) return null; if (typeof value !== 'string') throw new HttpError(400, 'Invalid text field', 'invalid_profile_field'); return value.trim().slice(0, max); }
function validateDestination(value: unknown): string | null { if (value === null || value === undefined || value === '') return null; if (typeof value !== 'string') throw new HttpError(400, 'Invalid URL', 'invalid_url'); let url: URL; try { url = new URL(value); } catch { throw new HttpError(400, 'Invalid URL', 'invalid_url'); } if (!['http:', 'https:'].includes(url.protocol)) throw new HttpError(400, 'Only HTTP(S) links are supported', 'invalid_url'); return url.toString(); }

export async function updateProfile(request: Request, env: Env, profileId: string): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const db = new Db(requireDb(env)); const profile = await requireEditableProfile(db, auth.user.id, profileId); const body = await readJson<{ displayName?: string; bio?: string; seoTitle?: string; seoDescription?: string }>(request); await db.run(`UPDATE profiles SET display_name = COALESCE(?, display_name), bio = COALESCE(?, bio), seo_title = ?, seo_description = ?, updated_at = ? WHERE id = ?`, [cleanText(body.displayName,80), cleanText(body.bio,500), cleanText(body.seoTitle,70), cleanText(body.seoDescription,180), new Date().toISOString(), profile.id]); return json({ ok: true, profileId: profile.id }); }
export async function addProfileBlock(request: Request, env: Env, profileId: string): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const db = new Db(requireDb(env)); await requireEditableProfile(db, auth.user.id, profileId); const body = await readJson<{ type?: string; title?: string; url?: string; config?: unknown }>(request); const allowed = new Set(['link','social_link','telegram','youtube','tiktok','instagram','facebook','reddit','linkedin','website','booking','custom_button','featured_article','featured_video','campaign_proof','media_kit','work_with_me','project_card','community_card','heading']); if (!body.type || !allowed.has(body.type)) throw new HttpError(400,'Unsupported profile block type','invalid_block_type'); const positionRow = await db.first<{ next_position:number }>(`SELECT COALESCE(MAX(position), -1) + 1 AS next_position FROM profile_blocks WHERE profile_id = ?`,[profileId]); const blockId=`blk_${crypto.randomUUID().replace(/-/g,'')}`; const timestamp=new Date().toISOString(); await db.run(`INSERT INTO profile_blocks (id, profile_id, block_type, position, enabled, title, url, config_json, created_at, updated_at) VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?, ?)`, [blockId, profileId, body.type, positionRow?.next_position || 0, cleanText(body.title,120), validateDestination(body.url), JSON.stringify(body.config || {}), timestamp, timestamp]); return json({ id:blockId },{status:201}); }
export async function updateProfileBlock(request: Request, env: Env, profileId: string, blockId: string): Promise<Response> { const auth=await requireAuth(request,env); await verifyCsrf(request,env,auth); const db=new Db(requireDb(env)); await requireEditableProfile(db,auth.user.id,profileId); if (!(await db.first<{id:string}>(`SELECT id FROM profile_blocks WHERE id = ? AND profile_id = ?`,[blockId,profileId]))) throw new HttpError(404,'Block not found','block_not_found'); const body=await readJson<{title?:string;url?:string|null;enabled?:boolean;config?:unknown}>(request); await db.run(`UPDATE profile_blocks SET title = COALESCE(?, title), url = COALESCE(?, url), enabled = COALESCE(?, enabled), config_json = COALESCE(?, config_json), updated_at = ? WHERE id = ? AND profile_id = ?`, [cleanText(body.title,120), body.url === undefined ? null : validateDestination(body.url), body.enabled === undefined ? null : (body.enabled ? 1 : 0), body.config === undefined ? null : JSON.stringify(body.config), new Date().toISOString(), blockId, profileId]); return json({ok:true}); }
export async function reorderProfileBlocks(request: Request, env: Env, profileId: string): Promise<Response> { const auth=await requireAuth(request,env); await verifyCsrf(request,env,auth); const db=new Db(requireDb(env)); await requireEditableProfile(db,auth.user.id,profileId); const body=await readJson<{blockIds?:string[]}>(request); if(!Array.isArray(body.blockIds)||new Set(body.blockIds).size!==body.blockIds.length||body.blockIds.length>100) throw new HttpError(400,'Invalid block order','invalid_block_order'); const current=await db.all<{id:string}>(`SELECT id FROM profile_blocks WHERE profile_id = ?`,[profileId]); if(current.length!==body.blockIds.length||current.some((row)=>!body.blockIds!.includes(row.id))) throw new HttpError(400,'Block order must include every profile block exactly once','invalid_block_order'); const timestamp=new Date().toISOString(); await db.batch(body.blockIds.map((blockId,position)=>db.statement(`UPDATE profile_blocks SET position = ?, updated_at = ? WHERE id = ? AND profile_id = ?`,[position,timestamp,blockId,profileId]))); return json({ok:true}); }
export async function deleteProfileBlock(request: Request, env: Env, profileId: string, blockId: string): Promise<Response> { const auth=await requireAuth(request,env); await verifyCsrf(request,env,auth); const db=new Db(requireDb(env)); await requireEditableProfile(db,auth.user.id,profileId); await db.run(`DELETE FROM profile_blocks WHERE id = ? AND profile_id = ?`,[blockId,profileId]); return json({ok:true}); }
export async function publishProfile(request: Request, env: Env, profileId: string, published: boolean): Promise<Response> { const auth=await requireAuth(request,env); await verifyCsrf(request,env,auth); const db=new Db(requireDb(env)); const profile=await requireEditableProfile(db,auth.user.id,profileId); if(profile.verification_status!=='verified_x') throw new HttpError(409,'Verified X ownership is required before publishing','verification_required'); const timestamp=new Date().toISOString(); await db.run(`UPDATE profiles SET visibility = ?, published_at = ?, updated_at = ? WHERE id = ?`,[published?'published':'private',published?timestamp:null,timestamp,profileId]); return json({ok:true,visibility:published?'published':'private'}); }
