import type { Env } from '../env';
import { requireDb } from '../env';
import { Db } from '../db/client';
import { HttpError, json, readJson } from '../http';
import { requireAuth, verifyCsrf } from '../auth/session';
import { randomToken, sha256 } from '../security/crypto';
import { organizationMembership } from './organizations';

const id = (prefix: string) => `${prefix}_${crypto.randomUUID().replace(/-/g, '')}`; const now = () => new Date().toISOString();
export async function createTrackedLink(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); await verifyCsrf(request, env, auth); const body = await readJson<{ activityId?: string }>(request); if (!body.activityId) throw new HttpError(400, 'activityId is required', 'activity_required'); const db = new Db(requireDb(env)); const activity = await db.first<{ campaign_id: string; organization_id: string; destination_url: string | null }>('SELECT a.campaign_id, c.organization_id, a.destination_url FROM campaign_activities a JOIN campaigns c ON c.id = a.campaign_id WHERE a.id = ?', [body.activityId]); if (!activity || !activity.destination_url) throw new HttpError(409, 'An activity destination URL is required', 'destination_required'); const membership = await organizationMembership(db, auth.user.id, activity.organization_id); if (!membership || !['owner', 'admin', 'marketing_manager'].includes(membership.role)) throw new HttpError(403, 'Tracking access denied', 'forbidden'); const code = randomToken(8); const linkId = id('tl'); const timestamp = now(); await db.run('INSERT INTO tracked_links (id, organization_id, campaign_id, activity_id, code, destination_url, status, created_by_user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, \'active\', ?, ?, ?)', [linkId, activity.organization_id, activity.campaign_id, body.activityId, code, activity.destination_url, auth.user.id, timestamp, timestamp]); const origin = new URL(request.url).origin; return json({ id: linkId, code, url: `${origin}/r/${encodeURIComponent(code)}` }, { status: 201 }); }
export async function listTrackedLinks(request: Request, env: Env): Promise<Response> { const auth = await requireAuth(request, env); const campaignId = new URL(request.url).searchParams.get('campaignId'); if (!campaignId) throw new HttpError(400, 'campaignId is required', 'campaign_required'); const db = new Db(requireDb(env)); const campaign = await db.first<{ organization_id: string }>('SELECT organization_id FROM campaigns WHERE id = ?', [campaignId]); if (!campaign || !(await organizationMembership(db, auth.user.id, campaign.organization_id))) throw new HttpError(403, 'Tracking access denied', 'forbidden'); return json({ links: await db.all('SELECT id, code, activity_id, destination_url, status, created_at FROM tracked_links WHERE campaign_id = ? ORDER BY created_at DESC', [campaignId]) }); }
export async function redirectTrackedLink(request: Request, env: Env, code: string): Promise<Response> { const db = new Db(requireDb(env)); const link = await db.first<{ id: string; destination_url: string; status: string }>('SELECT id, destination_url, status FROM tracked_links WHERE code = ?', [code]); if (!link || link.status !== 'active') throw new HttpError(404, 'Tracking link not found', 'tracking_not_found'); const visitor = request.headers.get('cf-connecting-ip') || request.headers.get('user-agent') || randomToken(12); const referer = request.headers.get('referer'); let referrerHost: string | null = null; try { if (referer) referrerHost = new URL(referer).hostname; } catch {} await db.run('INSERT INTO tracked_link_clicks (id, tracked_link_id, visitor_id_hash, referrer_host, occurred_at) VALUES (?, ?, ?, ?, ?)', [id('tlc'), link.id, await sha256(visitor), referrerHost, now()]); return Response.redirect(link.destination_url, 302); }
