import { useEffect, useMemo, useState } from 'react';
import FounderGrowthIntelligencePanel from './FounderGrowthIntelligencePanel';
import { ProductWorkspace, type ProductMe, type ProductProfile, type ProductStatus } from './ProductWorkspace';
import './analytics.css';

type Point = { month: string; count: number };
type SocialSource = { label: string; value: number; color?: string };
type SocialProfile = { platform: string; audience?: number; impressions?: number; engagements?: number; clicks?: number; status?: string };
type Analytics = { linkClicks: number; profileViews: number; sections: number; connectedChannels: number; monthlyClicks: Point[]; monthlyProfileViews: Point[]; platformClicks?: Array<{ platform: string; count: number }>; socialSources?: SocialSource[]; socialProfiles?: SocialProfile[]; proof?: { metrics: Array<{ label: string; value: string }> } | null };
type IconName = 'eye' | 'link' | 'users' | 'cube' | 'coin' | 'trend' | 'target' | 'check';

async function loadAnalytics(profileId: string): Promise<Analytics> {
  const response = await fetch(`/api/profiles/${encodeURIComponent(profileId)}/analytics`, { credentials: 'same-origin' });
  if (!response.ok) throw new Error('Analytics are not available yet.');
  return response.json() as Promise<Analytics>;
}

function Icon({ name }: { name: IconName }) {
  const paths = { eye: 'M2.5 12s3.6-6.5 9.5-6.5S21.5 12 21.5 12 17.9 18.5 12 18.5 2.5 12 2.5 12Zm12.5 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z', link: 'm10 13 4-4m-7.2 9.2-1.1 1.1a4.25 4.25 0 0 1-6-6l3.2-3.2a4.25 4.25 0 0 1 6 0m8.3-4.3 1.1-1.1a4.25 4.25 0 0 1 6 6l-3.2 3.2a4.25 4.25 0 0 1-6 0', users: 'M15.5 20v-1.4a4.5 4.5 0 0 0-4.5-4.5h-3a4.5 4.5 0 0 0-4.5 4.5V20m7.25-11.6a3.35 3.35 0 1 1-6.7 0 3.35 3.35 0 0 1 6.7 0ZM17.2 6.3a3.3 3.3 0 0 1 0 6.2m2.6 7.5v-1.1a4.45 4.45 0 0 0-2.5-4', cube: 'm12 2 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5m-18 0v8l9 5 9-5v-8', coin: 'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm3 7.5c-.2-1.2-1.1-2-3-2-1.7 0-2.8.8-2.8 2 0 3 5.8 1.5 5.8 5 0 1.2-1 2.1-2.9 2.1-1.8 0-3-.8-3.2-2.2M12 5.5v13', trend: 'M3 17l6-6 4 4 7-8M15 7h5v5', target: 'M12 2a10 10 0 1 0 10 10M12 6a6 6 0 1 0 6 6M12 10a2 2 0 1 0 2 2', check: 'm5 12 4 4L19 6' } as const;
  return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
}

function pathFor(points: Point[], width: number, height: number, max: number) {
  return points.map((point, index) => { const x = points.length <= 1 ? 0 : index / (points.length - 1) * width; const y = height - 20 - point.count / max * (height - 46); return `${index ? 'L' : 'M'}${x.toFixed(1)} ${y.toFixed(1)}`; }).join(' ');
}

function SoftLineChart({ views, clicks }: { views: Point[]; clicks: Point[] }) {
  const points = views.length ? views : clicks; const max = Math.max(1, ...views.map((point) => point.count), ...clicks.map((point) => point.count)); const width = 780; const height = 270;
  const [active, setActive] = useState<number | null>(null); const viewsPath = pathFor(points, width, height, max); const clickPoints = clicks.length ? clicks : points; const clickPath = pathFor(clickPoints, width, height, max); const nonZero = points.some((point) => point.count > 0) || clicks.some((point) => point.count > 0); const selected = active === null ? null : points[active]; const selectedClicks = active === null ? null : clickPoints[active]; const activeX = active === null || points.length <= 1 ? 0 : active / (points.length - 1) * width;
  return <div className="analytics-trend"><div className="analytics-legend"><span><i className="views" />Profile views</span><span><i className="clicks" />Link clicks</span><span className="muted"><i />Social engagement <b>Unavailable</b></span></div><div className="analytics-chart-stage" onPointerLeave={() => setActive(null)}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Interactive profile views and Linkary tracked clicks over time" preserveAspectRatio="none"><defs><linearGradient id="analytics-view-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#ff5b16" stopOpacity=".22" /><stop offset="1" stopColor="#ff5b16" stopOpacity="0" /></linearGradient></defs>{[.18,.46,.74].map((line) => <line key={line} className="analytics-gridline" x1="0" x2={width} y1={height * line} y2={height * line} />)}{nonZero && <><path d={`${viewsPath} L${width} ${height} L0 ${height}Z`} fill="url(#analytics-view-fill)" /><path className="analytics-view-line" d={viewsPath} /><path className="analytics-click-line" d={clickPath} /></>}{active !== null && <line className="analytics-active-line" x1={activeX} x2={activeX} y1="12" y2={height - 14} />}{points.map((point, index) => { const x = points.length <= 1 ? 0 : index / (points.length - 1) * width; const y = height - 20 - point.count / max * (height - 46); return <g key={point.month}><circle className={`analytics-point ${active === index ? 'active' : ''}`} cx={x} cy={y} r={active === index ? 5 : 3.2} /><rect className="analytics-hit" x={x - width / Math.max(12, points.length * 2)} y="8" width={width / Math.max(6, points.length)} height={height - 12} tabIndex={0} role="button" aria-label={`${point.month}: ${point.count} raw profile views and ${clickPoints[index]?.count || 0} tracked clicks`} onPointerEnter={() => setActive(index)} onPointerDown={() => setActive(index)} onFocus={() => setActive(index)} onBlur={() => setActive(null)} /></g>; })}</svg>{selected && <div className="analytics-tooltip" style={{ left: `${Math.min(88, Math.max(12, activeX / width * 100))}%` }} role="status"><strong>{new Date(`${selected.month}-01T00:00:00Z`).toLocaleDateString('en', { month: 'short', year: 'numeric', timeZone: 'UTC' })}</strong><span><i className="views" />{selected.count.toLocaleString()} profile views</span><span><i className="clicks" />{(selectedClicks?.count || 0).toLocaleString()} link clicks</span></div>}</div><div className="analytics-axis">{points.filter((_, index) => index % 3 === 0 || index === points.length - 1).map((point) => <span key={point.month}>{new Date(`${point.month}-01T00:00:00Z`).toLocaleDateString('en', { month: 'short', timeZone: 'UTC' })}</span>)}</div>{!nonZero && <p className="analytics-zero-note">No recorded profile views or tracked clicks in this period yet.</p>}</div>;
}

function SocialSources({ sources = [] }: { sources?: SocialSource[] }) {
  const rows = [['X data', 'Awaiting provider snapshot'], ['Telegram', 'Awaiting provider snapshot'], ['YouTube', 'Provider integration not enabled'], ['Instagram', 'Provider integration not enabled']]; const total = sources.reduce((sum, source) => sum + source.value, 0); const colors = ['#1769e8', '#23a5e8', '#ee4a7c', '#8a54ea', '#c7cfda']; let progress = 0;
  const segments = total ? sources.map((source, index) => { const start = progress; progress += source.value / total * 100; return `${source.color || colors[index % colors.length]} ${start}% ${progress}%`; }).join(',') : '';
  return <article className="analytics-panel analytics-audience"><header><div><h2>Audience & socials</h2><p>Connected sources populate automatically.</p></div><span>Provider data</span></header><div className={`analytics-donut ${total ? 'has-data' : ''}`} style={total ? { background: `conic-gradient(${segments})` } : undefined}><b>{total ? total.toLocaleString() : '—'}</b><small>{total ? 'provider\nsignals' : 'no provider\ndata yet'}</small></div><div className="analytics-social-list">{total ? sources.map((source, index) => <div key={source.label}><i style={{ background: source.color || colors[index % colors.length] }} /><strong>{source.label}</strong><small>{source.value.toLocaleString()} provider signals</small></div>) : rows.map(([label, state]) => <div key={label}><i /><strong>{label}</strong><small>{state}</small></div>)}</div></article>;
}

function SocialAnalytics({ profiles = [] }: { profiles?: SocialProfile[] }) {
  const platforms = [
    { platform: 'X data', short: 'X', color: '#121820', state: 'Awaiting X provider integration' },
    { platform: 'Telegram', short: 'TG', color: '#239bd8', state: 'Awaiting Telegram provider integration' },
    { platform: 'YouTube', short: 'YT', color: '#ff3d35', state: 'Awaiting YouTube provider integration' },
    { platform: 'Instagram', short: 'IG', color: '#d94d91', state: 'Awaiting Instagram provider integration' },
    { platform: 'TikTok', short: 'TT', color: '#1a1a1a', state: 'Awaiting TikTok provider integration' },
    { platform: 'LinkedIn', short: 'in', color: '#0a66c2', state: 'Awaiting LinkedIn provider integration' },
  ];
  const values = new Map(profiles.map((profile) => [profile.platform.toLowerCase(), profile]));
  return <article className="analytics-panel analytics-social-analytics"><header><div><h2>Social analytics</h2><p>Provider-authorized account metrics will populate these cards automatically.</p></div><span>Provider data</span></header><div className="analytics-social-cards">{platforms.map((platform) => { const profile = values.get(platform.platform.toLowerCase()); const hasData = Boolean(profile && [profile.audience, profile.impressions, profile.engagements, profile.clicks].some((value) => typeof value === 'number')); const format = (value: number | undefined) => typeof value === 'number' ? value.toLocaleString() : '—'; return <section className={`analytics-social-card ${hasData ? 'has-data' : ''}`} key={platform.platform}><div className="analytics-social-card-heading"><i style={{ background: platform.color }}>{platform.short}</i><div><strong>{platform.platform}</strong><small>{profile?.status || platform.state}</small></div></div><dl><div><dt>Audience</dt><dd>{format(profile?.audience)}</dd></div><div><dt>Impressions</dt><dd>{format(profile?.impressions)}</dd></div><div><dt>Engagements</dt><dd>{format(profile?.engagements)}</dd></div><div><dt>Link clicks</dt><dd>{format(profile?.clicks)}</dd></div></dl></section>; })}</div></article>;
}

export default function AnalyticsExperience({ me, status }: { me: ProductMe; status: ProductStatus }) {
  const first = status.profiles.find((item) => item.profile_type === 'creator') || status.profiles[0];
  const saved = typeof window === 'undefined' ? null : window.localStorage.getItem('linkary.active.profile');
  const [profileId, setProfileId] = useState(saved && status.profiles.some((item) => item.id === saved) ? saved : first?.id || '');
  const profile = status.profiles.find((item) => item.id === profileId) || first; const [analytics, setAnalytics] = useState<Analytics | null>(null); const [error, setError] = useState(false); const [tab, setTab] = useState<'overview' | 'social' | 'campaigns' | 'onchain'>('overview');
  useEffect(() => { if (!profile) return; setAnalytics(null); setError(false); void loadAnalytics(profile.id).then(setAnalytics).catch(() => setError(true)); }, [profile?.id]);
  const outcome = useMemo(() => analytics?.proof?.metrics.find((metric) => metric.label === 'Verified outcomes')?.value || 'Unavailable', [analytics]);
  if (!profile) return null;
  const metrics = [{ label: 'PROFILE VIEWS', value: analytics ? String(analytics.profileViews || 0) : '—', note: 'Raw public-profile views', icon: 'eye' as const }, { label: 'LINK CLICKS', value: analytics ? String(analytics.linkClicks || 0) : '—', note: 'Linkary tracked', icon: 'link' as const }, { label: 'ENGAGEMENTS', value: 'Unavailable', note: 'Social APIs not connected', icon: 'users' as const, status: 'Provider data' }, { label: 'VERIFIED OUTCOMES', value: outcome, note: outcome === 'Unavailable' ? 'No verified evidence yet' : 'Verified evidence', icon: 'cube' as const }, { label: 'ATTRIBUTED VALUE', value: 'Unavailable', note: profile.profile_type === 'project' ? 'See project intelligence below' : 'No campaign value recorded', icon: 'coin' as const }];
  function changeProfile(id: string) { setProfileId(id); window.localStorage.setItem('linkary.active.profile', id); }
  const destinations = analytics?.platformClicks || []; const destinationMax = Math.max(1, ...destinations.map((row) => row.count));
  const tabs = [['overview', 'Overview'], ['social', 'Social analytics'], ['campaigns', 'Campaigns & attribution'], ['onchain', 'Onchain & auctions']] as const;
  const contentLinks = <article className="analytics-panel"><header><div><h2>Top performing content</h2><p>Measured outbound destinations and links.</p></div><a href="/profile">Edit links →</a></header>{destinations.length ? <div className="analytics-rank-list">{destinations.slice(0, 5).map((row, index) => <div key={row.platform}><b>{index + 1}</b><span>{row.platform}</span><i><em style={{ width: `${row.count / destinationMax * 100}%` }} /></i><strong>{row.count}</strong></div>)}</div> : <p className="analytics-panel-empty">No tracked content clicks yet.</p>}</article>;
  const onchainActivity = <article className="analytics-panel"><header><div><h2>Onchain & auction activity</h2><p>Actual Linkary records only.</p></div><a href="/bids">View all →</a></header><div className="analytics-activity-list"><div><i><Icon name="trend" /></i><span><strong>Profile promotion auctions</strong><small>Live, next available and completed placements appear in Bids.</small></span></div><div><i><Icon name="target" /></i><span><strong>UTM attribution</strong><small>Tracked links populate campaign and source performance.</small></span></div><div><i><Icon name="check" /></i><span><strong>Evidence and outcomes</strong><small>Only verified or recorded outcomes are reported.</small></span></div></div></article>;
  const campaigns = <article className="analytics-panel"><header><div><h2>Top campaigns & partners</h2><p>Campaign intelligence is ready for tracked activity.</p></div><a href="/campaigns">View all →</a></header><div className="analytics-readiness"><div><i className="ready" />Linkary tracked clicks <small>Ready</small></div><div><i className="ready" />Raw profile views <small>Ready</small></div><div><i />X data <small>Awaiting integration</small></div><div><i />Telegram engagement <small>Awaiting integration</small></div></div></article>;
  return <ProductWorkspace me={me} status={status} profile={profile as ProductProfile} onProfileChange={changeProfile}><div className="ops-stack analytics-page"><header className="analytics-hero"><div><span className="ops-kicker">ANALYTICS</span><h1>Analytics Overview</h1><p>Track your profile, campaigns, attribution and onchain impact.</p></div><div className="analytics-actions"><span>All time · Linkary tracked</span><button type="button" className="ops-button primary" onClick={() => window.print()}>↓ Export report</button></div></header><nav className="analytics-tabs" aria-label="Analytics sections">{tabs.map(([id, label]) => <button key={id} type="button" className={tab === id ? 'active' : ''} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}>{label}</button>)}</nav>{error ? <section className="analytics-empty"><strong>Analytics are still warming up</strong><span>We could not load your recorded analytics right now. Your existing profile, wallet, campaign and auction data are unchanged.</span></section> : <>{tab === 'overview' && <><section className="analytics-kpis">{metrics.map((metric) => <article key={metric.label} className={`analytics-metric analytics-metric-${metric.icon}`}><i><Icon name={metric.icon} /></i><div><span>{metric.label}</span><strong className={metric.value === 'Unavailable' ? 'is-unavailable' : ''}>{metric.value}</strong><small>{metric.note}</small></div>{metric.status && <em>{metric.status}</em>}</article>)}</section><section className="analytics-primary-grid"><article className="analytics-panel analytics-performance"><header><div><h2>Performance over time</h2><p>Recorded profile views and outbound clicks.</p></div><span>Last 12 months</span></header>{analytics ? <SoftLineChart views={analytics.monthlyProfileViews || []} clicks={analytics.monthlyClicks || []} /> : <div className="analytics-chart-skeleton" />}</article><SocialSources sources={analytics?.socialSources} /></section><section className="analytics-lower-grid">{contentLinks}{onchainActivity}{campaigns}</section></>}{tab === 'social' && <SocialAnalytics profiles={analytics?.socialProfiles} />}{tab === 'campaigns' && <section className="analytics-lower-grid analytics-tab-grid">{contentLinks}{campaigns}</section>}{tab === 'onchain' && <section className="analytics-tab-grid"><div>{onchainActivity}</div>{profile.profile_type === 'project' && profile.organization_id ? <FounderGrowthIntelligencePanel organizationId={profile.organization_id} /> : <section className="analytics-empty"><strong>Onchain reporting is ready for Project workspaces</strong><span>Promotion auctions are visible above. Project campaign outcomes and verified onchain actions appear here when recorded.</span></section>}</section>}</>}</div></ProductWorkspace>;
}
