import { useEffect, useMemo, useState } from 'react';
import FounderGrowthIntelligencePanel from './FounderGrowthIntelligencePanel';
import { ProductWorkspace, type ProductMe, type ProductProfile, type ProductStatus } from './ProductWorkspace';
import './analytics.css';

type Analytics = { linkClicks: number; sections: number; connectedChannels: number; monthlyClicks: Array<{ month: string; count: number }>; platformClicks?: Array<{ platform: string; count: number }> };

async function loadAnalytics(profileId: string): Promise<Analytics> {
  const response = await fetch(`/api/profiles/${encodeURIComponent(profileId)}/analytics`, { credentials: 'same-origin' });
  if (!response.ok) throw new Error('Analytics are not available yet.');
  return response.json() as Promise<Analytics>;
}

function TrendChart({ points }: { points: Analytics['monthlyClicks'] }) {
  const values = points.map((point) => point.count); const max = Math.max(...values, 1); const width = 760; const height = 190;
  const path = values.map((value, index) => { const x = values.length <= 1 ? 0 : (index / (values.length - 1)) * width; const y = height - 18 - (value / max) * (height - 38); return `${index === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`; }).join(' ');
  return <div className="analytics-chart" aria-label="Profile link clicks over the last twelve months"><svg viewBox={`0 0 ${width} ${height}`} role="img" preserveAspectRatio="none"><defs><linearGradient id="analytics-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff5b16" stopOpacity=".22" /><stop offset="1" stopColor="#ff5b16" stopOpacity="0" /></linearGradient></defs>{[.25, .5, .75].map((line) => <line key={line} x1="0" x2={width} y1={height * line} y2={height * line} className="analytics-gridline" />)}<path d={`${path} L ${width} ${height} L 0 ${height} Z`} fill="url(#analytics-fill)" /><path d={path} className="analytics-line" />{values.map((value, index) => { const x = values.length <= 1 ? 0 : (index / (values.length - 1)) * width; const y = height - 18 - (value / max) * (height - 38); return <circle key={`${index}-${value}`} cx={x} cy={y} r="3.5" className="analytics-dot"><title>{`${points[index]?.month}: ${value} clicks`}</title></circle>; })}</svg><div className="analytics-axis">{points.filter((_, index) => index % 3 === 0).map((point) => <span key={point.month}>{point.month}</span>)}</div></div>;
}

export default function AnalyticsExperience({ me, status }: { me: ProductMe; status: ProductStatus }) {
  const first = status.profiles.find((item) => item.profile_type === 'creator') || status.profiles[0];
  const saved = typeof window !== 'undefined' ? window.localStorage.getItem('linkary.active.profile') : null;
  const [profileId, setProfileId] = useState(saved && status.profiles.some((item) => item.id === saved) ? saved : first?.id || '');
  const profile = status.profiles.find((item) => item.id === profileId) || first; const [analytics, setAnalytics] = useState<Analytics | null>(null); const [error, setError] = useState(false);
  useEffect(() => { if (!profile) return; setAnalytics(null); setError(false); void loadAnalytics(profile.id).then(setAnalytics).catch(() => setError(true)); }, [profile?.id]);
  const total = useMemo(() => analytics?.monthlyClicks.reduce((sum, point) => sum + point.count, 0) || 0, [analytics]); if (!profile) return null;
  function changeProfile(id: string) { setProfileId(id); window.localStorage.setItem('linkary.active.profile', id); }
  return <ProductWorkspace me={me} status={status} profile={profile as ProductProfile} onProfileChange={changeProfile}><div className="ops-stack analytics-page"><header className="analytics-hero"><div><span className="ops-kicker">ANALYTICS</span><h1>Real data. Real growth.</h1><p>Understand your Linkary audience, campaign distribution and attributable activity.</p></div><button type="button" className="ops-button secondary" onClick={() => window.print()}>Export view</button></header>{error ? <section className="analytics-empty"><strong>Analytics are still warming up</strong><span>Once people visit your profile or use a tracked link, the trend will appear here.</span></section> : <><section className="analytics-kpis"><article><span>LINK CLICKS</span><strong>{analytics?.linkClicks ?? '—'}</strong><small>Linkary tracked activity</small></article><article><span>CONTENT SECTIONS</span><strong>{analytics?.sections ?? '—'}</strong><small>Published destinations</small></article><article><span>CONNECTED CHANNELS</span><strong>{analytics?.connectedChannels ?? '—'}</strong><small>Social destinations</small></article><article><span>12-MONTH ACTIVITY</span><strong>{analytics ? total : '—'}</strong><small>Recorded clicks</small></article></section><section className="ops-card analytics-card"><div className="analytics-card-head"><div><span className="ops-kicker">PROFILE GROWTH · 12 MONTHS</span><h2>Link clicks over time</h2></div><span className="analytics-source">Linkary tracked · X data when connected · UTC</span></div>{analytics ? <TrendChart points={analytics.monthlyClicks} /> : <div className="analytics-chart-skeleton" />}</section>{analytics?.platformClicks?.length ? <section className="ops-card analytics-sources"><div><span className="ops-kicker">TOP DESTINATIONS</span><h2>Where your audience clicks</h2></div>{analytics.platformClicks.map((item) => <div className="analytics-source-row" key={item.platform}><span>{item.platform}</span><strong>{item.count}</strong><i style={{ width: `${Math.min(100, (item.count / Math.max(...analytics.platformClicks!.map((entry) => entry.count), 1)) * 100)}%` }} /></div>)}</section> : null}</>}{profile.profile_type === 'project' && profile.organization_id ? <FounderGrowthIntelligencePanel organizationId={profile.organization_id} /> : <section className="analytics-note"><strong>Campaign and UTM attribution</strong><span>Project workspaces will see campaign results, creator tracking links, UTMs, outcomes and auction activity here as those events are recorded.</span></section>}</div></ProductWorkspace>;
}
