import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ProductWorkspace, type ProductMe, type ProductProfile, type ProductStatus } from './ProductWorkspace';

type Role = 'owner' | 'admin' | 'marketing_manager' | 'analyst' | 'viewer';
type Project = { id: string; name: string; status: string; verification_status: string; role: Role; username?: string | null };
type Campaign = { id: string; name: string; objective: string; budget_usd: number | null; status: string; starts_at: string | null; ends_at: string | null; created_at: string; source_type: string; execution_mode: string };
type Opportunity = { id: string; campaign_id: string; organization_id: string; title: string; brief: string; compensation_text: string; deliverables_text: string; status: string; application_deadline: string | null; campaign_name: string; project_name?: string; applications: number };
type Manager = { id: string; profile_id: string; manager_type: string; display_name: string };

class ApiError extends Error { constructor(readonly code: string, message: string) { super(message); } }
async function api<T>(path: string, init?: RequestInit): Promise<T> { const headers = new Headers(init?.headers); if (init?.body && !headers.has('content-type')) headers.set('content-type','application/json'); const response = await fetch(path,{...init,headers,credentials:'same-origin'}); const payload=(await response.json().catch(()=>({}))) as {error?:string;message?:string}&T; if(!response.ok) throw new ApiError(payload.error||'request_failed',payload.message||'Request failed'); return payload; }
function cookie(){const hit=document.cookie.split('; ').find((part)=>part.startsWith('__Host-linkary_csrf='));return hit?decodeURIComponent(hit.split('=').slice(1).join('=')):null;}
function human(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase());}
function money(value:number|null){return value===null?'Not set':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);}
function date(value:string|null){if(!value)return 'Not set';const d=new Date(value);return Number.isNaN(d.getTime())?'Not set':new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(d);}
function writable(project?:Project){return Boolean(project&&project.status==='active'&&project.verification_status==='verified_x'&&['owner','admin','marketing_manager'].includes(project.role));}

const sourceOptions=[['external','External / already running'],['internal_team','My team'],['agency','Agency'],['creator_kol','Creator / KOL'],['community','Community'],['launchpad','Launchpad / growth platform'],['linkary','Linkary'],['other','Other']];

export default function GrowthExperience({me,status}:{me:ProductMe;status:ProductStatus}){
 const navigate=useNavigate();
 const creatorFirst=status.profiles.find((p)=>p.profile_type==='creator')||status.profiles[0];
 const stored=window.localStorage.getItem('linkary.active.profile');
 const [profileId,setProfileId]=useState(stored&&status.profiles.some((p)=>p.id===stored)?stored:creatorFirst?.id||'');
 const profile=status.profiles.find((p)=>p.id===profileId)||creatorFirst;
 const personalProfile=status.profiles.find((p)=>p.profile_type==='creator');
 const [projects,setProjects]=useState<Project[]>([]); const [projectId,setProjectId]=useState(''); const project=projects.find((p)=>p.id===projectId);
 const [tab,setTab]=useState<'tracking'|'opportunities'>('tracking'); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [opportunities,setOpportunities]=useState<Opportunity[]>([]); const [managers,setManagers]=useState<Manager[]>([]);
 const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [showCampaign,setShowCampaign]=useState(false); const [showOpportunity,setShowOpportunity]=useState<Campaign|null>(null); const [applyTo,setApplyTo]=useState<Opportunity|null>(null);
 const [campaignForm,setCampaignForm]=useState({name:'',objective:'',budgetUsd:'',sourceType:'external',executionMode:'tracked_elsewhere'});
 const [oppForm,setOppForm]=useState({title:'',brief:'',compensationText:'',deliverablesText:'',deadline:''}); const [applyForm,setApplyForm]=useState({managerId:'',note:''});
 const myManagers=useMemo(()=>personalProfile?managers.filter((m)=>m.profile_id===personalProfile.id):[],[managers,personalProfile?.id]);
 function changeProfile(id:string){setProfileId(id);window.localStorage.setItem('linkary.active.profile',id);const selected=status.profiles.find((p)=>p.id===id);if(selected?.organization_id&&projects.some((p)=>p.id===selected.organization_id))setProjectId(selected.organization_id);}
 useEffect(()=>{api<{organizations:Project[]}>('/api/organizations').then((r)=>{setProjects(r.organizations);const chosen=profile?.organization_id&&r.organizations.some((p)=>p.id===profile.organization_id)?profile.organization_id:r.organizations[0]?.id||'';setProjectId(chosen);}).catch(()=>setMessage('Project access is temporarily unavailable.'));api<{managers:Manager[]}>('/api/partner-managers').then((r)=>setManagers(r.managers)).catch(()=>undefined);},[]);
 useEffect(()=>{if(profile?.organization_id&&projects.some((p)=>p.id===profile.organization_id))setProjectId(profile.organization_id);},[profileId,projects.length]);
 async function loadCampaigns(){if(!projectId){setCampaigns([]);return;}setLoading(true);setMessage('');try{const r=await api<{campaigns:Campaign[]}>(`/api/campaigns?organizationId=${encodeURIComponent(projectId)}`);setCampaigns(r.campaigns);}catch(e){setMessage(e instanceof ApiError&&e.code==='project_verification_required'?'Verify this Project with its official X identity to start tracking growth.':'Growth records are temporarily unavailable.');}finally{setLoading(false);}}
 async function loadOpportunities(){setLoading(true);setMessage('');try{const r=projectId?await api<{opportunities:Opportunity[]}>(`/api/campaign-opportunities?organizationId=${encodeURIComponent(projectId)}`):await api<{opportunities:Opportunity[]}>('/api/campaign-opportunities');setOpportunities(r.opportunities);}catch{setMessage('Campaign opportunities are temporarily unavailable.');}finally{setLoading(false);}}
 useEffect(()=>{if(tab==='tracking')void loadCampaigns();else void loadOpportunities();},[projectId,tab]);
 async function addCampaign(event:React.FormEvent){event.preventDefault();const token=cookie();if(!token||!projectId)return;setMessage('');try{await api('/api/campaigns',{method:'POST',headers:{'x-csrf-token':token},body:JSON.stringify({organizationId:projectId,name:campaignForm.name,objective:campaignForm.objective,budgetUsd:campaignForm.budgetUsd?Number(campaignForm.budgetUsd):undefined,sourceType:campaignForm.sourceType,executionMode:campaignForm.executionMode})});setCampaignForm({name:'',objective:'',budgetUsd:'',sourceType:'external',executionMode:'tracked_elsewhere'});setShowCampaign(false);setMessage('Campaign added to Growth Tracking.');await loadCampaigns();}catch(e){setMessage(e instanceof ApiError&&e.code==='project_verification_required'?'Verify this Project with its official X identity before adding growth records.':'The campaign could not be added.');}}
 function openOpportunity(campaign:Campaign){setShowOpportunity(campaign);setOppForm({title:campaign.name,brief:campaign.objective,compensationText:'',deliverablesText:'',deadline:''});}
 async function publishOpportunity(event:React.FormEvent){event.preventDefault();const token=cookie();if(!token||!showOpportunity)return;try{await api('/api/campaign-opportunities',{method:'POST',headers:{'x-csrf-token':token},body:JSON.stringify({campaignId:showOpportunity.id,title:oppForm.title,brief:oppForm.brief,compensationText:oppForm.compensationText,deliverablesText:oppForm.deliverablesText,applicationDeadline:oppForm.deadline||null,status:'open'})});setShowOpportunity(null);setMessage('Campaign opportunity is now open on Linkary.');setTab('opportunities');}catch(e){setMessage(e instanceof ApiError&&e.code==='opportunity_exists'?'This campaign already has an opportunity.':'The opportunity could not be published.');}}
 async function apply(event:React.FormEvent){event.preventDefault();const token=cookie();if(!token||!applyTo||!personalProfile)return;try{await api('/api/campaign-opportunity-applications',{method:'POST',headers:{'x-csrf-token':token},body:JSON.stringify({opportunityId:applyTo.id,profileId:personalProfile.id,managerId:applyForm.managerId||null,note:applyForm.note})});setApplyTo(null);setApplyForm({managerId:'',note:''});setMessage('Application sent. The Project team can review it inside Linkary.');}catch{setMessage('Your application could not be sent.');}}
 if(!profile)return null;
 return <ProductWorkspace me={me} status={status} profile={profile as ProductProfile} onProfileChange={changeProfile}><div className="ops-stack growth-workspace">
  <div className="ops-heading-row"><div><span className="ops-kicker">GROWTH INTELLIGENCE</span><h1>Track growth wherever it happens</h1><p>Add campaigns you already run through agencies, creators, communities, launchpads or your own team. Linkary turns the activity into attribution and reusable intelligence.</p></div>{tab==='tracking'&&writable(project)&&<button className="ops-button primary" onClick={()=>setShowCampaign(true)}>+ Add campaign</button>}</div>
  <section className="growth-principle"><strong>Run anywhere. Track here.</strong><span>Campaign execution on Linkary is optional. Tracking, evidence and relationship intelligence remain the core product.</span></section>
  <div className="ops-project-toolbar"><div><span className="ops-kicker">PROJECT</span>{projects.length>1?<select value={projectId} onChange={(e)=>setProjectId(e.target.value)}>{projects.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:<strong>{project?.name||'No Project selected'}</strong>}</div>{project&&<div className={`ops-project-state ${project.verification_status==='verified_x'?'verified':'pending'}`}>{project.verification_status==='verified_x'?'Verified on X':'X verification required'}</div>}</div>
  <nav className="ops-tabs growth-tabs"><button className={tab==='tracking'?'active':''} onClick={()=>setTab('tracking')}>Tracked campaigns</button><button className={tab==='opportunities'?'active':''} onClick={()=>setTab('opportunities')}>Campaign opportunities</button></nav>
  {message&&<div className="ops-message">{message}</div>}
  {tab==='tracking'?<section className="ops-section"><div className="ops-section-title"><div><h2>Growth records</h2><p>External campaigns and Linkary-run campaigns live in the same evidence layer.</p></div></div>{loading?<div className="ops-loading">Loading growth records...</div>:!campaigns.length?<div className="ops-empty"><div className="ops-empty-icon">◇</div><h3>No campaigns tracked yet</h3><p>Add something you are already running. You do not need to run the campaign through Linkary.</p>{writable(project)&&<button className="ops-button secondary" onClick={()=>setShowCampaign(true)}>Add first campaign</button>}</div>:<div className="growth-campaign-list">{campaigns.map((c)=><article key={c.id}><div className="growth-campaign-main"><div className="growth-campaign-tags"><span>{human(c.source_type)}</span><span>{c.execution_mode==='run_on_linkary'?'Running on Linkary':'Tracked externally'}</span></div><h3>{c.name}</h3><p>{c.objective||'No objective added.'}</p></div><div className="growth-campaign-stats"><div><span>BUDGET</span><strong>{money(c.budget_usd)}</strong></div><div><span>STATUS</span><strong>{human(c.status)}</strong></div></div><div className="growth-campaign-actions"><button onClick={()=>navigate(`/tracking?campaign=${encodeURIComponent(c.id)}&project=${encodeURIComponent(projectId)}`)}>Open tracking</button>{writable(project)&&<button onClick={()=>openOpportunity(c)}>Open as opportunity</button>}</div></article>)}</div>}</section>:<section className="ops-section"><div className="ops-section-title"><div><h2>Optional campaign marketplace</h2><p>Projects can open selected campaigns for creators or manager portfolios. This is an additional execution feature, not the core Linkary workflow.</p></div></div>{loading?<div className="ops-loading">Loading opportunities...</div>:!opportunities.length?<div className="ops-empty"><div className="ops-empty-icon">＋</div><h3>No opportunities here yet</h3><p>{projectId?'Open one of your tracked campaigns when you want creators or managers to participate directly through Linkary.':'Open opportunities will appear here.'}</p></div>:<div className="growth-opportunity-grid">{opportunities.map((o)=><article key={o.id}><div className="growth-campaign-tags"><span>{o.project_name||project?.name||'Project'}</span><span>{human(o.status)}</span></div><h3>{o.title}</h3><p>{o.brief||'No brief added.'}</p><div className="growth-opportunity-meta"><span>{o.compensation_text||'Compensation not specified'}</span><span>{o.application_deadline?`Apply by ${date(o.application_deadline)}`:'No deadline'}</span></div><div className="growth-campaign-actions">{personalProfile&&o.status==='open'&&<button onClick={()=>setApplyTo(o)}>Apply / accept</button>}<span>{o.applications||0} applications</span></div></article>)}</div>}</section>}
  {showCampaign&&<div className="ops-modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)setShowCampaign(false);}}><form className="ops-modal" onSubmit={addCampaign}><div className="ops-modal-head"><div><span className="ops-kicker">ADD TO GROWTH TRACKING</span><h2>Where is this campaign running?</h2></div><button type="button" onClick={()=>setShowCampaign(false)}>×</button></div><label>Campaign name<input value={campaignForm.name} onChange={(e)=>setCampaignForm({...campaignForm,name:e.target.value})} required placeholder="Example: TGE creator push"/></label><div className="ops-field-grid two"><label>Source<select value={campaignForm.sourceType} onChange={(e)=>setCampaignForm({...campaignForm,sourceType:e.target.value})}>{sourceOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>How will it run?<select value={campaignForm.executionMode} onChange={(e)=>setCampaignForm({...campaignForm,executionMode:e.target.value})}><option value="tracked_elsewhere">Run elsewhere, track in Linkary</option><option value="run_on_linkary">Run through Linkary</option></select></label></div><label>Objective<textarea value={campaignForm.objective} onChange={(e)=>setCampaignForm({...campaignForm,objective:e.target.value})} placeholder="What result matters? Registrations, joins, deposits, purchases, users..."/></label><label>Budget, optional<input type="number" min="0" step="0.01" value={campaignForm.budgetUsd} onChange={(e)=>setCampaignForm({...campaignForm,budgetUsd:e.target.value})}/></label><div className="ops-form-actions"><button type="button" className="ops-button ghost" onClick={()=>setShowCampaign(false)}>Cancel</button><button className="ops-button primary">Add campaign</button></div></form></div>}
  {showOpportunity&&<div className="ops-modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)setShowOpportunity(null);}}><form className="ops-modal" onSubmit={publishOpportunity}><div className="ops-modal-head"><div><span className="ops-kicker">OPTIONAL EXECUTION</span><h2>Open campaign to Linkary partners</h2></div><button type="button" onClick={()=>setShowOpportunity(null)}>×</button></div><label>Opportunity title<input value={oppForm.title} onChange={(e)=>setOppForm({...oppForm,title:e.target.value})} required/></label><label>Brief<textarea value={oppForm.brief} onChange={(e)=>setOppForm({...oppForm,brief:e.target.value})}/></label><label>Deliverables<textarea value={oppForm.deliverablesText} onChange={(e)=>setOppForm({...oppForm,deliverablesText:e.target.value})} placeholder="Example: X thread, Telegram post, short video..."/></label><label>Compensation / deal structure<input value={oppForm.compensationText} onChange={(e)=>setOppForm({...oppForm,compensationText:e.target.value})} placeholder="Example: $500 USDT, token allocation, or discuss"/></label><label>Application deadline<input type="date" value={oppForm.deadline} onChange={(e)=>setOppForm({...oppForm,deadline:e.target.value})}/></label><div className="ops-form-actions"><button type="button" className="ops-button ghost" onClick={()=>setShowOpportunity(null)}>Cancel</button><button className="ops-button primary">Publish opportunity</button></div></form></div>}
  {applyTo&&personalProfile&&<div className="ops-modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)setApplyTo(null);}}><form className="ops-modal" onSubmit={apply}><div className="ops-modal-head"><div><span className="ops-kicker">CAMPAIGN OPPORTUNITY</span><h2>{applyTo.title}</h2></div><button type="button" onClick={()=>setApplyTo(null)}>×</button></div>{myManagers.length>0&&<label>Apply as<select value={applyForm.managerId} onChange={(e)=>setApplyForm({...applyForm,managerId:e.target.value})}><option value="">{personalProfile.display_name} · Creator</option>{myManagers.map((m)=><option key={m.id} value={m.id}>{m.display_name} · {human(m.manager_type)}</option>)}</select></label>}<label>Note<textarea value={applyForm.note} onChange={(e)=>setApplyForm({...applyForm,note:e.target.value})} placeholder="Why are you a fit, expected reach, proposed approach..."/></label><div className="ops-form-actions"><button type="button" className="ops-button ghost" onClick={()=>setApplyTo(null)}>Cancel</button><button className="ops-button primary">Send application</button></div></form></div>}
 </div></ProductWorkspace>;
}
