import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ProductWorkspace, type ProductMe, type ProductProfile, type ProductStatus } from './ProductWorkspace';

type Role = 'owner' | 'admin' | 'marketing_manager' | 'analyst' | 'viewer';
type Project = { id: string; name: string; status: string; verification_status: string; role: Role; username?: string | null };
type Campaign = { id: string; name: string; objective: string; budget_usd: number | null; status: string; starts_at: string | null; ends_at: string | null; created_at: string; source_type: string; execution_mode: string };
type Opportunity = { id: string; campaign_id: string; organization_id: string; title: string; brief: string; compensation_text: string; deliverables_text: string; status: string; application_deadline: string | null; campaign_name: string; project_name?: string; applications: number };
type Manager = { id: string; profile_id: string; manager_type: string; display_name: string };
type OutcomeSummary = { conversions: number; value_usd: number; tracked_clicks: number; tracking_links: number; conversion_rate: number };
type ReportRow = Campaign & { summary: OutcomeSummary };
type NetworkEntity = { id: string; entity_type: 'creator' | 'community'; display_name: string; primary_handle: string | null; activity_count: number; tracked_clicks: number; outcomes: number; attributed_value: number };
type SourcePerformance = { source: string; campaigns: number; spend: number; clicks: number; outcomes: number; value: number };

class ApiError extends Error { constructor(readonly code: string, message: string) { super(message); } }
async function api<T>(path: string, init?: RequestInit): Promise<T> { const headers = new Headers(init?.headers); if (init?.body && !headers.has('content-type')) headers.set('content-type','application/json'); const response = await fetch(path,{...init,headers,credentials:'same-origin'}); const payload=(await response.json().catch(()=>({}))) as {error?:string;message?:string}&T; if(!response.ok) throw new ApiError(payload.error||'request_failed',payload.message||'Request failed'); return payload; }
function cookie(){const hit=document.cookie.split('; ').find((part)=>part.startsWith('__Host-linkary_csrf='));return hit?decodeURIComponent(hit.split('=').slice(1).join('=')):null;}
function human(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase());}
function money(value:number|null){return value===null?'Not set':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);}
function date(value:string|null){if(!value)return 'Not set';const d=new Date(value);return Number.isNaN(d.getTime())?'Not set':new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(d);}
function writable(project?:Project){return Boolean(project&&project.status==='active'&&project.verification_status==='verified_x'&&['owner','admin','marketing_manager'].includes(project.role));}
function csvCell(value: unknown){return `"${String(value ?? '').replace(/"/g,'""')}"`;}

const sourceOptions=[['external','External / already running'],['internal_team','My team'],['agency','Agency'],['creator_kol','Creator / KOL'],['community','Community'],['launchpad','Launchpad / growth platform'],['linkary','Linkary'],['other','Other']];
const emptySummary: OutcomeSummary={conversions:0,value_usd:0,tracked_clicks:0,tracking_links:0,conversion_rate:0};

export default function GrowthExperience({me,status}:{me:ProductMe;status:ProductStatus}){
 const navigate=useNavigate();
 const creatorFirst=status.profiles.find((p)=>p.profile_type==='creator')||status.profiles[0];const projectFirst=status.profiles.find((p)=>p.profile_type==='project')||creatorFirst;
 const stored=window.localStorage.getItem('linkary.active.profile');
 const [profileId,setProfileId]=useState(stored&&status.profiles.some((p)=>p.id===stored&&p.profile_type==='project')?stored:projectFirst?.id||'');
 const profile=status.profiles.find((p)=>p.id===profileId)||projectFirst;
 const personalProfile=status.profiles.find((p)=>p.profile_type==='creator');
 const [projects,setProjects]=useState<Project[]>([]); const [projectId,setProjectId]=useState(''); const project=projects.find((p)=>p.id===projectId);
 const [tab,setTab]=useState<'tracking'|'report'|'opportunities'>('tracking'); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [opportunities,setOpportunities]=useState<Opportunity[]>([]); const [managers,setManagers]=useState<Manager[]>([]);
 const [reportRows,setReportRows]=useState<ReportRow[]>([]); const [reportPartners,setReportPartners]=useState<NetworkEntity[]>([]);
 const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [showCampaign,setShowCampaign]=useState(false); const [showOpportunity,setShowOpportunity]=useState<Campaign|null>(null); const [applyTo,setApplyTo]=useState<Opportunity|null>(null);
 const [campaignForm,setCampaignForm]=useState({name:'',objective:'',budgetUsd:'',sourceType:'external',executionMode:'tracked_elsewhere'});
 const [oppForm,setOppForm]=useState({title:'',brief:'',compensationText:'',deliverablesText:'',deadline:''}); const [applyForm,setApplyForm]=useState({managerId:'',note:''});
 const myManagers=useMemo(()=>personalProfile?managers.filter((m)=>m.profile_id===personalProfile.id):[],[managers,personalProfile?.id]);
 const reportTotals=useMemo(()=>reportRows.reduce((acc,row)=>{acc.spend+=Number(row.budget_usd||0);acc.clicks+=Number(row.summary.tracked_clicks||0);acc.outcomes+=Number(row.summary.conversions||0);acc.value+=Number(row.summary.value_usd||0);return acc;},{spend:0,clicks:0,outcomes:0,value:0}),[reportRows]);
 const reportRoi=reportTotals.spend>0?reportTotals.value/reportTotals.spend:null;
 const reportConversion=reportTotals.clicks>0?reportTotals.outcomes/reportTotals.clicks:null;
 const costPerOutcome=reportTotals.outcomes>0&&reportTotals.spend>0?reportTotals.spend/reportTotals.outcomes:null;
 const sourcePerformance=useMemo(()=>{const grouped=new Map<string,SourcePerformance>();for(const row of reportRows){const key=row.source_type||'other';const current=grouped.get(key)||{source:key,campaigns:0,spend:0,clicks:0,outcomes:0,value:0};current.campaigns+=1;current.spend+=Number(row.budget_usd||0);current.clicks+=Number(row.summary.tracked_clicks||0);current.outcomes+=Number(row.summary.conversions||0);current.value+=Number(row.summary.value_usd||0);grouped.set(key,current);}return Array.from(grouped.values()).sort((a,b)=>b.value-a.value||b.outcomes-a.outcomes||b.clicks-a.clicks);},[reportRows]);
 function changeProfile(id:string){setProfileId(id);window.localStorage.setItem('linkary.active.profile',id);const selected=status.profiles.find((p)=>p.id===id);if(selected?.organization_id&&projects.some((p)=>p.id===selected.organization_id))setProjectId(selected.organization_id);}
 useEffect(()=>{api<{organizations:Project[]}>('/api/organizations').then((r)=>{setProjects(r.organizations);const chosen=profile?.organization_id&&r.organizations.some((p)=>p.id===profile.organization_id)?profile.organization_id:r.organizations[0]?.id||'';setProjectId(chosen);}).catch(()=>setMessage('Project access is temporarily unavailable.'));api<{managers:Manager[]}>('/api/partner-managers').then((r)=>setManagers(r.managers)).catch(()=>undefined);},[]);
 useEffect(()=>{if(profile?.organization_id&&projects.some((p)=>p.id===profile.organization_id))setProjectId(profile.organization_id);},[profileId,projects.length]);
 async function loadCampaigns(){if(!projectId){setCampaigns([]);return;}setLoading(true);setMessage('');try{const r=await api<{campaigns:Campaign[]}>(`/api/campaigns?organizationId=${encodeURIComponent(projectId)}`);setCampaigns(r.campaigns);}catch(e){setMessage(e instanceof ApiError&&e.code==='project_verification_required'?'Verify this Project with its official X identity to start tracking growth.':'Growth records are temporarily unavailable.');}finally{setLoading(false);}}
 async function loadOpportunities(){setLoading(true);setMessage('');try{const r=projectId?await api<{opportunities:Opportunity[]}>(`/api/campaign-opportunities?organizationId=${encodeURIComponent(projectId)}`):await api<{opportunities:Opportunity[]}>('/api/campaign-opportunities');setOpportunities(r.opportunities);}catch{setMessage('Campaign opportunities are temporarily unavailable.');}finally{setLoading(false);}}
 async function loadReport(){if(!projectId){setReportRows([]);setReportPartners([]);return;}setLoading(true);setMessage('');try{const campaignResult=await api<{campaigns:Campaign[]}>(`/api/campaigns?organizationId=${encodeURIComponent(projectId)}`);const [summaries,partnerResult]=await Promise.all([Promise.all(campaignResult.campaigns.map((campaign)=>api<{summary:OutcomeSummary}>(`/api/campaign-outcomes?campaignId=${encodeURIComponent(campaign.id)}`).then((result)=>result.summary).catch(()=>emptySummary))),api<{entities:NetworkEntity[]}>(`/api/network-entities?organizationId=${encodeURIComponent(projectId)}`).catch(()=>({entities:[]}))]);setCampaigns(campaignResult.campaigns);setReportRows(campaignResult.campaigns.map((campaign,index)=>({...campaign,summary:summaries[index]||emptySummary})));setReportPartners(partnerResult.entities.sort((a,b)=>Number(b.attributed_value||0)-Number(a.attributed_value||0)||Number(b.outcomes||0)-Number(a.outcomes||0)||Number(b.tracked_clicks||0)-Number(a.tracked_clicks||0)));}catch{setMessage('The growth report is temporarily unavailable.');}finally{setLoading(false);}}
 useEffect(()=>{if(tab==='tracking')void loadCampaigns();else if(tab==='report')void loadReport();else void loadOpportunities();},[projectId,tab]);
 async function addCampaign(event:React.FormEvent){event.preventDefault();const token=cookie();if(!token||!projectId)return;setMessage('');try{await api('/api/campaigns',{method:'POST',headers:{'x-csrf-token':token},body:JSON.stringify({organizationId:projectId,name:campaignForm.name,objective:campaignForm.objective,budgetUsd:campaignForm.budgetUsd?Number(campaignForm.budgetUsd):undefined,sourceType:campaignForm.sourceType,executionMode:campaignForm.executionMode})});setCampaignForm({name:'',objective:'',budgetUsd:'',sourceType:'external',executionMode:'tracked_elsewhere'});setShowCampaign(false);setMessage('Campaign added to Growth.');await loadCampaigns();}catch(e){setMessage(e instanceof ApiError&&e.code==='project_verification_required'?'Verify this Project with its official X identity before adding growth records.':'The campaign could not be added.');}}
 function openOpportunity(campaign:Campaign){setShowOpportunity(campaign);setOppForm({title:campaign.name,brief:campaign.objective,compensationText:'',deliverablesText:'',deadline:''});}
 async function publishOpportunity(event:React.FormEvent){event.preventDefault();const token=cookie();if(!token||!showOpportunity)return;try{await api('/api/campaign-opportunities',{method:'POST',headers:{'x-csrf-token':token},body:JSON.stringify({campaignId:showOpportunity.id,title:oppForm.title,brief:oppForm.brief,compensationText:oppForm.compensationText,deliverablesText:oppForm.deliverablesText,applicationDeadline:oppForm.deadline||null,status:'open'})});setShowOpportunity(null);setMessage('Campaign opportunity is now open on Linkary.');setTab('opportunities');}catch(e){setMessage(e instanceof ApiError&&e.code==='opportunity_exists'?'This campaign already has an opportunity.':'The opportunity could not be published.');}}
 async function apply(event:React.FormEvent){event.preventDefault();const token=cookie();if(!token||!applyTo||!personalProfile)return;try{await api('/api/campaign-opportunity-applications',{method:'POST',headers:{'x-csrf-token':token},body:JSON.stringify({opportunityId:applyTo.id,profileId:personalProfile.id,managerId:applyForm.managerId||null,note:applyForm.note})});setApplyTo(null);setApplyForm({managerId:'',note:''});setMessage('Application sent. The Project team can review it inside Linkary.');}catch{setMessage('Your application could not be sent.');}}
 async function copyReport(){const text=[`${project?.name||'Project'} growth report`,`Spend: ${money(reportTotals.spend)}`,`Tracked clicks: ${reportTotals.clicks.toLocaleString()}`,`Outcomes: ${reportTotals.outcomes.toLocaleString()}`,`Attributed value: ${money(reportTotals.value)}`,`Return on spend: ${reportRoi===null?'Not available':`${reportRoi.toFixed(2)}x`}`].join('\n');try{await navigator.clipboard.writeText(text);setMessage('Growth summary copied.');}catch{setMessage('Copy is unavailable in this browser.');}}
 function downloadReport(){const header=['Campaign','Source','Status','Spend USD','Tracked clicks','Outcomes','Attributed value USD','Return on spend'];const rows=reportRows.map((row)=>[row.name,human(row.source_type),human(row.status),Number(row.budget_usd||0),Number(row.summary.tracked_clicks||0),Number(row.summary.conversions||0),Number(row.summary.value_usd||0),row.budget_usd&&row.budget_usd>0?(Number(row.summary.value_usd||0)/row.budget_usd).toFixed(2):'']);const csv=[header,...rows].map((row)=>row.map(csvCell).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${(project?.name||'linkary-project').toLowerCase().replace(/[^a-z0-9]+/g,'-')}-growth-report.csv`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
 if(!profile)return null;
 return <ProductWorkspace me={me} status={status} profile={profile as ProductProfile} onProfileChange={changeProfile}><div className="ops-stack growth-workspace">
  <div className="ops-heading-row"><div><span className="ops-kicker">GROWTH</span><h1>Track growth wherever it happens</h1><p>Add campaigns you already run through agencies, creators, communities, launchpads or your own team. Linkary turns the activity into clear evidence, outcomes and reusable intelligence.</p></div>{tab==='tracking'&&writable(project)&&<button className="ops-button primary" onClick={()=>setShowCampaign(true)}>+ Add campaign</button>}</div>
  <section className="growth-principle"><strong>Run anywhere. Track here.</strong><span>Running a campaign through Linkary is optional. Your growth history, partner performance and outcomes stay in one place either way.</span></section>
  <div className="ops-project-toolbar"><div><span className="ops-kicker">PROJECT</span>{projects.length>1?<select value={projectId} onChange={(e)=>setProjectId(e.target.value)}>{projects.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:<strong>{project?.name||'No Project selected'}</strong>}</div>{project&&<div className={`ops-project-state ${project.verification_status==='verified_x'?'verified':'pending'}`}>{project.verification_status==='verified_x'?'Verified on X':'X verification required'}</div>}</div>
  <nav className="ops-tabs growth-tabs"><button className={tab==='tracking'?'active':''} onClick={()=>setTab('tracking')}>Campaigns</button><button className={tab==='report'?'active':''} onClick={()=>setTab('report')}>Growth report</button><button className={tab==='opportunities'?'active':''} onClick={()=>setTab('opportunities')}>Opportunities</button></nav>
  {message&&<div className="ops-message">{message}</div>}
  {tab==='tracking'?<section className="ops-section"><div className="ops-section-title"><div><h2>Campaigns</h2><p>External campaigns and Linkary-run campaigns belong to the same growth history.</p></div></div>{loading?<div className="ops-loading">Loading campaigns...</div>:!campaigns.length?<div className="ops-empty"><div className="ops-empty-icon">◇</div><h3>No campaigns tracked yet</h3><p>Add something you are already running. You do not need to run the campaign through Linkary.</p>{writable(project)&&<button className="ops-button secondary" onClick={()=>setShowCampaign(true)}>Add first campaign</button>}</div>:<div className="growth-campaign-list">{campaigns.map((c)=><article key={c.id}><div className="growth-campaign-main"><div className="growth-campaign-tags"><span>{human(c.source_type)}</span><span>{c.execution_mode==='run_on_linkary'?'Running on Linkary':'Tracked externally'}</span></div><h3>{c.name}</h3><p>{c.objective||'No objective added.'}</p></div><div className="growth-campaign-stats"><div><span>BUDGET</span><strong>{money(c.budget_usd)}</strong></div><div><span>STATUS</span><strong>{human(c.status)}</strong></div></div><div className="growth-campaign-actions"><button onClick={()=>navigate(`/tracking?campaign=${encodeURIComponent(c.id)}&project=${encodeURIComponent(projectId)}`)}>Open details</button>{writable(project)&&<button onClick={()=>openOpportunity(c)}>Open as opportunity</button>}</div></article>)}</div>}</section>:tab==='report'?<div className="growth-report-stack">
    <div className="growth-report-actions"><div><h2>Founder growth report</h2><p>See what you spent, what moved, and which channels and partners created measurable results.</p></div><div><button className="ops-button secondary" onClick={()=>void copyReport()} disabled={loading||!reportRows.length}>Copy summary</button><button className="ops-button primary" onClick={downloadReport} disabled={loading||!reportRows.length}>Download CSV</button></div></div>
    {loading?<div className="ops-loading">Building your growth report...</div>:!reportRows.length?<section className="ops-empty prominent"><div className="ops-empty-icon">◇</div><h3>No report yet</h3><p>Add campaigns and tracking evidence first. Your report will build automatically from real Linkary data.</p>{writable(project)&&<button className="ops-button primary" onClick={()=>setTab('tracking')}>Add campaign</button>}</section>:<>
      <section className="ops-metrics growth-report-metrics"><article><span>TRACKED SPEND</span><strong>{money(reportTotals.spend)}</strong><small>{reportRows.length} campaign{reportRows.length===1?'':'s'}</small></article><article><span>CLICKS</span><strong>{reportTotals.clicks.toLocaleString()}</strong><small>Measured visits</small></article><article><span>OUTCOMES</span><strong>{reportTotals.outcomes.toLocaleString()}</strong><small>{reportConversion===null?'No click data':`${(reportConversion*100).toFixed(1)}% conversion`}</small></article><article><span>ATTRIBUTED VALUE</span><strong>{money(reportTotals.value)}</strong><small>{reportRoi===null?'Add campaign spend for ROI':`${reportRoi.toFixed(2)}x return on spend`}</small></article></section>
      <section className="growth-report-insight"><div><span>RETURN ON SPEND</span><strong>{reportRoi===null?'Not available':`${reportRoi.toFixed(2)}x`}</strong></div><div><span>COST PER OUTCOME</span><strong>{costPerOutcome===null?'Not available':money(costPerOutcome)}</strong></div><div><span>BEST CHANNEL</span><strong>{sourcePerformance[0]?human(sourcePerformance[0].source):'Not enough data'}</strong></div><p>These figures only use recorded Linkary evidence. Missing spend or outcome data is left out rather than estimated.</p></section>
      <section className="ops-section"><div className="ops-section-title"><div><h2>Campaign comparison</h2><p>Compare spend and measured outcomes campaign by campaign.</p></div></div><div className="growth-report-table"><div className="growth-report-row header"><span>Campaign</span><span>Source</span><span>Spend</span><span>Clicks</span><span>Outcomes</span><span>Value</span><span>Return</span></div>{reportRows.map((row)=>{const roi=row.budget_usd&&row.budget_usd>0?Number(row.summary.value_usd||0)/row.budget_usd:null;return <article className="growth-report-row" key={row.id}><div><strong>{row.name}</strong><small>{human(row.status)}</small></div><span>{human(row.source_type)}</span><strong>{money(Number(row.budget_usd||0))}</strong><strong>{Number(row.summary.tracked_clicks||0).toLocaleString()}</strong><strong>{Number(row.summary.conversions||0).toLocaleString()}</strong><strong>{money(Number(row.summary.value_usd||0))}</strong><strong>{roi===null?'N/A':`${roi.toFixed(2)}x`}</strong></article>})}</div></section>
      <div className="growth-report-grid"><section className="ops-section"><div className="ops-section-title"><div><h2>Channel performance</h2><p>See which sources are producing measurable value.</p></div></div><div className="growth-source-list">{sourcePerformance.map((source)=><article key={source.source}><div><strong>{human(source.source)}</strong><small>{source.campaigns} campaign{source.campaigns===1?'':'s'}</small></div><div><span>{source.clicks.toLocaleString()} clicks</span><span>{source.outcomes.toLocaleString()} outcomes</span><strong>{money(source.value)}</strong></div></article>)}</div></section>
      <section className="ops-section"><div className="ops-section-title"><div><h2>Partner performance</h2><p>Creators and communities ranked by recorded contribution.</p></div></div>{!reportPartners.length?<div className="ops-empty compact"><p>Attach creators or communities to campaign activities to see partner-level performance here.</p></div>:<div className="growth-partner-list">{reportPartners.slice(0,10).map((partner)=><article key={partner.id}><div><strong>{partner.display_name}</strong><small>{human(partner.entity_type)}{partner.primary_handle?` · @${partner.primary_handle}`:''}</small></div><div><span>{Number(partner.tracked_clicks||0).toLocaleString()} clicks</span><span>{Number(partner.outcomes||0).toLocaleString()} outcomes</span><strong>{money(Number(partner.attributed_value||0))}</strong></div></article>)}</div>}</section></div>
    </>}
  </div>:<section className="ops-section"><div className="ops-section-title"><div><h2>Optional campaign opportunities</h2><p>Open selected campaigns to creators or manager portfolios when you want to execute through Linkary.</p></div></div>{loading?<div className="ops-loading">Loading opportunities...</div>:!opportunities.length?<div className="ops-empty"><div className="ops-empty-icon">＋</div><h3>No opportunities here yet</h3><p>{projectId?'Open one of your campaigns when you want creators or managers to participate directly through Linkary.':'Open opportunities will appear here.'}</p></div>:<div className="growth-opportunity-grid">{opportunities.map((o)=><article key={o.id}><div className="growth-campaign-tags"><span>{o.project_name||project?.name||'Project'}</span><span>{human(o.status)}</span></div><h3>{o.title}</h3><p>{o.brief||'No brief added.'}</p><div className="growth-opportunity-meta"><span>{o.compensation_text||'Compensation not specified'}</span><span>{o.application_deadline?`Apply by ${date(o.application_deadline)}`:'No deadline'}</span></div><div className="growth-campaign-actions">{personalProfile&&o.status==='open'&&<button onClick={()=>setApplyTo(o)}>Apply / accept</button>}<span>{o.applications||0} applications</span></div></article>)}</div>}</section>}
  {showCampaign&&<div className="ops-modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)setShowCampaign(false);}}><form className="ops-modal" onSubmit={addCampaign}><div className="ops-modal-head"><div><span className="ops-kicker">ADD CAMPAIGN</span><h2>Where is this campaign running?</h2></div><button type="button" onClick={()=>setShowCampaign(false)}>×</button></div><label>Campaign name<input value={campaignForm.name} onChange={(e)=>setCampaignForm({...campaignForm,name:e.target.value})} required placeholder="Example: TGE creator push"/></label><div className="ops-field-grid two"><label>Source<select value={campaignForm.sourceType} onChange={(e)=>setCampaignForm({...campaignForm,sourceType:e.target.value})}>{sourceOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>How will it run?<select value={campaignForm.executionMode} onChange={(e)=>setCampaignForm({...campaignForm,executionMode:e.target.value})}><option value="tracked_elsewhere">Run elsewhere, track in Linkary</option><option value="run_on_linkary">Run through Linkary</option></select></label></div><label>Objective<textarea value={campaignForm.objective} onChange={(e)=>setCampaignForm({...campaignForm,objective:e.target.value})} placeholder="What result matters? Registrations, joins, deposits, purchases, users..."/></label><label>Budget, optional<input type="number" min="0" step="0.01" value={campaignForm.budgetUsd} onChange={(e)=>setCampaignForm({...campaignForm,budgetUsd:e.target.value})}/></label><div className="ops-form-actions"><button type="button" className="ops-button ghost" onClick={()=>setShowCampaign(false)}>Cancel</button><button className="ops-button primary">Add campaign</button></div></form></div>}
  {showOpportunity&&<div className="ops-modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)setShowOpportunity(null);}}><form className="ops-modal" onSubmit={publishOpportunity}><div className="ops-modal-head"><div><span className="ops-kicker">OPTIONAL EXECUTION</span><h2>Open campaign to Linkary partners</h2></div><button type="button" onClick={()=>setShowOpportunity(null)}>×</button></div><label>Opportunity title<input value={oppForm.title} onChange={(e)=>setOppForm({...oppForm,title:e.target.value})} required/></label><label>Brief<textarea value={oppForm.brief} onChange={(e)=>setOppForm({...oppForm,brief:e.target.value})}/></label><label>Deliverables<textarea value={oppForm.deliverablesText} onChange={(e)=>setOppForm({...oppForm,deliverablesText:e.target.value})} placeholder="Example: X thread, Telegram post, short video..."/></label><label>Compensation / deal structure<input value={oppForm.compensationText} onChange={(e)=>setOppForm({...oppForm,compensationText:e.target.value})} placeholder="Example: $500 USDT, token allocation, or discuss"/></label><label>Application deadline<input type="date" value={oppForm.deadline} onChange={(e)=>setOppForm({...oppForm,deadline:e.target.value})}/></label><div className="ops-form-actions"><button type="button" className="ops-button ghost" onClick={()=>setShowOpportunity(null)}>Cancel</button><button className="ops-button primary">Publish opportunity</button></div></form></div>}
  {applyTo&&personalProfile&&<div className="ops-modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)setApplyTo(null);}}><form className="ops-modal" onSubmit={apply}><div className="ops-modal-head"><div><span className="ops-kicker">CAMPAIGN OPPORTUNITY</span><h2>{applyTo.title}</h2></div><button type="button" onClick={()=>setApplyTo(null)}>×</button></div>{myManagers.length>0&&<label>Apply as<select value={applyForm.managerId} onChange={(e)=>setApplyForm({...applyForm,managerId:e.target.value})}><option value="">{personalProfile.display_name} · Creator</option>{myManagers.map((m)=><option key={m.id} value={m.id}>{m.display_name} · {human(m.manager_type)}</option>)}</select></label>}<label>Note<textarea value={applyForm.note} onChange={(e)=>setApplyForm({...applyForm,note:e.target.value})} placeholder="Why are you a fit, expected reach, proposed approach..."/></label><div className="ops-form-actions"><button type="button" className="ops-button ghost" onClick={()=>setApplyTo(null)}>Cancel</button><button className="ops-button primary">Send application</button></div></form></div>}
 </div></ProductWorkspace>;
}
